author,updated_at,like_count,text,public
@joel9616,2023-09-13T07:56:18Z,0,Can someone share the script to bifurcate the train and test images along with the labels in their respective folder i.e train and test folders. Thanks!,True
@Mrduirk,2022-08-07T10:36:56Z,0,como podria entrenar un imge datafolder con epochs en tensorflow?,True
@annie157,2022-07-29T13:39:46Z,0,Hey!  can you please help me out on how to get the confusion matrix for tensorflow object detection API??,True
@alirezamilani3561,2022-03-15T18:24:23Z,0,"Hi, Could you please help me? By running the ""generate_tfrecord.py"" I become this error :  (Python36) C:\Users\TEMP\Desktop\object_detection>python generate_tfrecord.py Traceback (most recent call last):   File ""generate_tfrecord.py"", line 23, in <module>     flags = tf.app.flags AttributeError: module 'tensorflow' has no attribute 'app'",True
@beaustrom923,2021-11-03T15:39:28Z,0,Thanks for the tutorial :),True
@kittydon777,2021-03-21T12:47:33Z,0,"Traceback (most recent call last):   File ""C:/Users/user/PycharmProjects/donut/generate_tfrecords.py"", line 108, in <module>     tf.app.run()   File ""C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\platform\app.py"", line 40, in run     _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)   File ""C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\absl\app.py"", line 303, in run     _run_main(main, args)   File ""C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\absl\app.py"", line 251, in _run_main     sys.exit(main(argv))   File ""C:/Users/user/PycharmProjects/donut/generate_tfrecords.py"", line 99, in main     tf_example = create_tf_example(group, path)   File ""C:/Users/user/PycharmProjects/donut/generate_tfrecords.py"", line 50, in create_tf_example     encoded_jpg = fid.read()   File ""C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\lib\io\file_io.py"", line 117, in read     self._preread_check()   File ""C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\lib\io\file_io.py"", line 79, in _preread_check     self._read_buf = _pywrap_file_io.BufferedInputStream( UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcd in position 58: invalid continuation byte   This is THE mistake, which I met. Have had smb such mistake?",True
@hiteshyerekar9810,2021-03-14T11:23:12Z,0,Great Tutorial .,True
@yassyoutube,2021-03-12T09:25:19Z,0,"Hello, I’ve been getting an error while running generate_tfrecord.py :  UnicodeDecodeError ‘utf-8’ codec can’t decode byte 0xe9 in position 78: invalid continuation byte  I’m working with tensorflow 2.4.1 - python 3.8.5 and win7-64   I tried to look everywhere for a solution but couldn’t find any  I would really appreciate some help 😭😭",True
@chrismckinley3110,2021-01-29T01:53:53Z,0,"I am getting a ""Module Not Found Error: No module named 'object_detection'"" it seems the generate_tfrecord.py does not know what to do with from object_detection.utils import dataset_util anyone come across this?",True
@kousailatidjet7294,2021-01-21T09:07:27Z,0,I got some features depricated. you were working in whitch python version?,True
@user-yt4jv8ju4w,2020-12-24T12:58:24Z,0,anyway,True
@blabber92,2020-08-07T17:33:44Z,0,can you release a video how to visualize the TFRecord images before we mode on to modeling,True
@iliaskhan8817,2020-07-06T06:24:54Z,0,"why i am getting only 'filename,width,height,class,xmin,ymin,xmax,ymax` this in test_labels?",True
@fatima-oz3ne,2020-06-18T13:37:29Z,0,HELLP MY HERO PLEASE HELP ME!!!! This work in windows ?? And you used SSD ??,True
@IgorBeduin,2020-05-20T00:17:17Z,12,tf.app was removed from TF2 so if you are having any issue with it just  import tensorflow.compat.v1 as tf  instead of  the usual  import tensorflow as tf you are running legacy stuff from TF1 but should work fine,True
@maxinteltech3321,2020-05-17T19:02:53Z,0,"@sentdex  Would u plz help? How can I fix this error when running xml_to_csv.py? ""IndexError: child index out of range""",True
@sapthamihirani4580,2020-04-29T21:08:55Z,0,Can someone tell me how to calculate the accuracy of the model I created? is there any function that I can use,True
@GOBish23,2020-04-26T16:18:52Z,0,"Thanks for this great tutorial series. Could you explain how you would add a set of custom labeled images to an already existing model so that the existing model can be improved with the custom images?  At the same time, would it be possible to remove classes of images from the already existing model so it only trains on the classes you want? Thanks!",True
@harshzota161,2020-04-24T17:49:15Z,0,"Traceback (most recent call last):   File ""C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py"", line 58, in <module>     from tensorflow.python.pywrap_tensorflow_internal import *   File ""C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py"", line 28, in <module>     _pywrap_tensorflow_internal = swig_import_helper()   File ""C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py"", line 24, in swig_import_helper     _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)   File ""C:\Program Files\Python37\lib\imp.py"", line 243, in load_module     return load_dynamic(name, filename, file)   File ""C:\Program Files\Python37\lib\imp.py"", line 343, in load_dynamic     return _load(spec) ImportError: DLL load failed: The specified module could not be found.  During handling of the above exception, another exception occurred:  Traceback (most recent call last):   File ""C:\tensorflow1\generate_tfrecord.py"", line 17, in <module>     import tensorflow as tf   File ""C:\Program Files\Python37\lib\site-packages\tensorflow\__init__.py"", line 101, in <module>     from tensorflow_core import *   File ""C:\Program Files\Python37\lib\site-packages\tensorflow_core\__init__.py"", line 40, in <module>     from tensorflow.python.tools import module_util as _module_util   File ""C:\Program Files\Python37\lib\site-packages\tensorflow\__init__.py"", line 50, in __getattr__     module = self._load()   File ""C:\Program Files\Python37\lib\site-packages\tensorflow\__init__.py"", line 44, in _load     module = _importlib.import_module(self.__name__)   File ""C:\Program Files\Python37\lib\importlib\__init__.py"", line 127, in import_module     return _bootstrap._gcd_import(name[level:], package, level)   File ""C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\__init__.py"", line 49, in <module>     from tensorflow.python import pywrap_tensorflow   File ""C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py"", line 74, in <module>     raise ImportError(msg) ImportError: Traceback (most recent call last):   File ""C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py"", line 58, in <module>     from tensorflow.python.pywrap_tensorflow_internal import *   File ""C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py"", line 28, in <module>     _pywrap_tensorflow_internal = swig_import_helper()   File ""C:\Program Files\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py"", line 24, in swig_import_helper     _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)   File ""C:\Program Files\Python37\lib\imp.py"", line 243, in load_module     return load_dynamic(name, filename, file)   File ""C:\Program Files\Python37\lib\imp.py"", line 343, in load_dynamic     return _load(spec) ImportError: DLL load failed: The specified module could not be found.   Failed to load the native TensorFlow runtime.       While running I got this error , please help anyone",True
@harshzota161,2020-04-24T17:09:07Z,0,Where do you keep thee generate_tfrecords file??,True
@harshzota161,2020-04-24T17:08:35Z,0,"HI I ran this on windows , I ran my cmd in object-detection and my tf_records file was outside the models folder in the tensroflow folder I have made, but I am getting no output , noo error but no output. @Sentdex please help",True
@user-wq4vn1zy5h,2020-04-21T07:03:43Z,1,"if your code don't execute at ""python3 generate_tfrecord.py --csv_input=data/train_labels.csv  --output_path=data/train.record"" you need to add --image_dir=images/ like""python3 generate_tfrecord.py --csv_input=data/train_labels.csv  --output_path=data/train.record --image_dir=images/"" then It will execute!! :)",True
@amarlearning,2020-04-19T13:15:12Z,0,"consfused about setup.py file at 12:30, read full steps here https://pythonprogramming.net/creating-tfrecord-files-tensorflow-object-detection-api-tutorial/ and https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md   hope this helps :)",True
@sakshijain1715,2020-04-12T17:41:18Z,1,"Hey thanks for the tutorial,Actually I am not getting any error but my train_label.csv as output is empty any idea why",True
@aariba1091,2020-03-31T21:00:07Z,0,"Hello everyone and @sentdex .   I'm getting a      File ""generate_tfrecord.py"", line 23, in <module>     flags = tf.app.flags AttributeError: module 'tensorflow' has no attribute 'app'   error.   How do I fix this?    Please help.   Many thanks in advance.",True
@FreeLearnclass,2020-03-25T17:29:28Z,0,what is the default input size / image size for training the model ? can i change it to something bigger or smaller ?,True
@parttimedude5440,2020-03-11T04:34:35Z,0,Which tensorflow version you are using ??,True
@hajeralsalman7697,2020-03-07T18:10:14Z,1,"When I run xml_to_csv.py I get ""IndexError: child index out of range"", does anyone know how to solve this error??",True
@shouryasimha8941,2020-02-19T21:14:51Z,0,"Hi, I have an annotation file x,y coordinates and images file and would like to map the annotations file with images as they are one to one? how to do this in python?",True
@lakshay510,2020-02-19T10:55:41Z,1,"Had filename error as I was using already annotated file from COCO, How to resolve it? Just remember to add  filename, xmin,ymin,xmax,ymax in your csv file.",True
@KSK414,2020-02-18T00:04:04Z,1,Anyone getting a ModuleNotFoundError: No module named 'tensorflow' error ?  while generating the tfrecord ?,True
@shikshajaiswal4405,2020-02-01T20:17:42Z,1,Anybody facing problem in generating tfrecords?  It keeps saying object_detection module not found (even though I installed it).,True
@dennis8213,2020-01-30T14:27:14Z,4,"The script has been updated.  Now you can set the path of your image directory in the python3 command. It would look sth like that: ""python3 generate_tfrecord.py --csv_input=data/train_labels.csv  --output_path=data/train.record --image_dir=images/train/""  And if you are using the newer version of Tensorflow, some parts have to be updated:  - The removed tf.app, so you have to build your FLAGS with the open source library, which looks very similar: https://abseil.io/docs/python/guides/flags  - For the other errors that will occur, just update tf to tf.compat.v1, example: tf.gfile.GFile() becomes tf.compat.v1.gfile.GFile(......)  tf.python_io.TFRecordWriter(FLAGS.output_path) becomes tf.compat.v1.python_io.TFRecordWriter(FLAGS.output_path)  And don't forget to update the last row to ""app.run(main)"" instead of ""tf.app.run()""  I hope this helps!!",True
@abdulsemedyasin2975,2020-01-15T17:28:18Z,0,"help i have this error and i don't know how to fix it   tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: images/07060_Produkt.jpg : The system cannot find the file specified. ; No such file or directory",True
@aakaashasa329,2020-01-07T09:08:52Z,4,"Hey, Which module I have to install for  'app' in flags = tf.app.flags",True
@Nalanaij,2019-12-22T19:22:20Z,1,"Hej, thank your for your good guides! I tried this with tensorflow 2.0.0, but since 2.0.0-beta1 the tensorflow.contrib is removed and train.py as well as model_mail.py (esp model_lib [also model_lib_v2) don't work anymore. Do you know what these are exactly doing and could you tell *us* ? regards!",True
@gokulnath4509,2019-12-22T05:03:08Z,0,"i got tain.recoed and test.record files along with these in colab what to d0?   WARNING:tensorflow:From /content/generate_tfrecord.py:100: The name tf.app.run is deprecated. Please use tf.compat.v1.app.run instead.  WARNING:tensorflow:From /content/generate_tfrecord.py:86: The name tf.python_io.TFRecordWriter is deprecated. Please use tf.io.TFRecordWriter instead.  W1222 05:01:11.972996 139857048823680 module_wrapper.py:139] From /content/generate_tfrecord.py:86: The name tf.python_io.TFRecordWriter is deprecated. Please use tf.io.TFRecordWriter instead.  WARNING:tensorflow:From /content/generate_tfrecord.py:45: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.  W1222 05:01:12.032250 139857048823680 module_wrapper.py:139] From /content/generate_tfrecord.py:45: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.  Traceback (most recent call last):   File ""/content/generate_tfrecord.py"", line 100, in <module>     tf.app.run()   File ""/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/platform/app.py"", line 40, in run     _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)   File ""/usr/local/lib/python3.6/dist-packages/absl/app.py"", line 299, in run     _run_main(main, args)   File ""/usr/local/lib/python3.6/dist-packages/absl/app.py"", line 250, in _run_main     sys.exit(main(argv))   File ""/content/generate_tfrecord.py"", line 91, in main     tf_example = create_tf_example(group, path)   File ""/content/generate_tfrecord.py"", line 46, in create_tf_example     encoded_jpg = fid.read()   File ""/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/lib/io/file_io.py"", line 122, in read     self._preread_check()   File ""/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/lib/io/file_io.py"", line 84, in _preread_check     compat.as_bytes(self.__name), 1024 * 512) tensorflow.python.framework.errors_impl.NotFoundError: 0185982_630x355.jpg; No such file or directory",True
@gokulnath4509,2019-12-22T04:35:58Z,0,"python /content/generate_tfrecord.py --csv_input=content/data/test_labels.csv  --output_path=content/data/test.record I got this error in Colab.How to solve thtis and run in colab?    File ""<ipython-input-42-81d1ebd64a7f>"", line 1     python /content/generate_tfrecord.py --csv_input=content/data/test_labels.csv  --output_path=content/data/test.record                                                                                                                          ^ SyntaxError: can't assign to operator",True
@zerohour2751,2019-12-14T16:37:20Z,1,hi sentdex   am getting this error when trying run the tf record.   tensorflow.python.framework.errors_impl.NotFoundError: ; No such file or directory   thanks in advance,True
@vignashrs,2019-12-12T10:49:29Z,0,"Any one please help me out from the error which i couldn't overcome for a week???   after using the below command    python3 generate_tfrecord.py --csv_input=data/train_labels.csv --output_path=data/train.record --image_dir=images/   I received the following error   Traceback (most recent call last):   File ""generate_tfrecord.py"", line 16, in <module>     import tensorflow as tf ImportError: No module named tensorflow   To overcome this error????",True
@ad2271188,2019-12-08T16:45:16Z,0,"Hey , thanks for the wonderful tutorial. At 10:18 , How do you change generate_tfrecord.py , in case of multiple object instances in a single image ?",True
@SandwichMitGurke,2019-11-30T10:27:02Z,2,"Edit: I've downgraded tensorflow and it worked   it doesn't seem to work with tensorflow 2.0 I get this error:     File ""generate_tfrecord.py"", line 22, in <module>     flags = tf.app.flags AttributeError: module 'tensorflow' has no attribute 'app'",True
@SandwichMitGurke,2019-11-27T19:05:33Z,0,i'm trying to detect cs:go enemies with this :D,True
@whoisjohngalt1942,2019-11-06T01:42:22Z,6,"If you're using Tensorflow 2.0 you will get errors saying things like Attributeerror: module tensorflow has no attribute 'app'.  File ""generate_tfrecords.py"", line 23, in <module>. You will need to make the following changes in generate_tfrecord.py:  tf.app.flags > tf.compat.v1.flags tf.gfile.GFile > tf.io.gfile.GFile tf.python_io.TFRecordWriter > tf.compat.v1.python_io.TFRecordWrite tf.app.run() >  tf.compat.v1.app.run()",True
@TGC40401,2019-10-30T04:57:36Z,0,"You may need to tweak generate_tfrecord to the new tensorflow if your're getting the ""tf has no attribute..."" message",True
@trannhien5179,2019-10-15T06:00:41Z,1,How to get train.py file?? I am stucl at the last.. Please help me..,True
@tanujkamde3557,2019-10-04T15:40:16Z,1,"Please help me for this error:- python3 generate_tfrecord.py --csv_input=data/train_labels.csv  --output_path=data/train.record --image_dir=images/train/   Traceback (most recent call last):   File ""generate_tfrecord.py"", line 102, in <module>     tf.app.run()   File ""/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py"", line 126, in run     _sys.exit(main(argv))   File ""generate_tfrecord.py"", line 93, in main     tf_example = create_tf_example(group, path)   File ""generate_tfrecord.py"", line 82, in create_tf_example     'image/object/class/label': dataset_util.int64_list_feature(classes),   File ""/usr/local/lib/python3.6/dist-packages/object_detection-0.1-py3.6.egg/object_detection/utils/dataset_util.py"", line 26, in int64_list_feature     return tf.train.Feature(int64_list=tf.train.Int64List(value=value)) TypeError: None has type NoneType, but expected one of: int, long",True
@divyanshumishra6292,2019-09-24T05:59:30Z,1,"Make sure you type the correct label map for e.g macncheese in the class_text_to_int function otherwise it will throw a comment like ""TypeError: None has type <class 'NoneType'>, but expected one of: (<class 'int'>,)"" .",True
@ikarton,2019-08-27T15:04:36Z,0,"Очень благодарен вам за этот наглядный пример +  за ""Text tutorial""",True
@djnx7680,2019-08-07T05:31:55Z,0,"generate_tfrecord.py   from object_detection.utils import dataset_util   Traceback (most recent call last):   File ""generate_tfrecord.py"", line 20, in <module>     from object_detection.utils import dataset_util ModuleNotFoundError: No module named 'object_detection'",True
@MachineWala1,2019-07-28T15:35:20Z,1,tf record file generates of 0 kb please help me,True
@kiranrao9314,2019-06-27T11:42:47Z,0,"Hello, Thanks for the tutorial.. Will it work in Ubuntu version 18?",True
@tunkyi7162,2019-06-21T15:01:27Z,1,"for those who got these errors open the xml_to_csv.py and change the index position of memeber[4][0] to member[1][0]. Change all the 4 values to 1. Hope u get solved! fTraceback (most recent call last):   File ""xml_to_csv.py"", line 36, in <module>     main()   File ""xml_to_csv.py"", line 31, in main     xml_df = xml_to_csv(image_path)   File ""xml_to_csv.py"", line 17, in xml_to_csv     int(member[4][0].text), IndexError: child index out of range",True
@RishabhBisht1997,2019-06-18T07:31:21Z,2,try doing the setup.py installation in the models/research folder's cmd if encountering error,True
@UvanSankar,2019-05-29T17:53:14Z,1,What Linux Distro r u using ?,True
@gunarakulangunaretnam3353,2019-05-16T14:21:58Z,1,How to count objects in video frame?,True
@jannicklawson5392,2019-05-14T19:41:11Z,0,When I'm trying to execute generate_tf_records with the specified parameters it just does nothing... What am I doing wrong? :(,True
@RowdyReview,2019-05-14T06:35:12Z,0,"check the below video for  How To Train an Object Detection Classifier Using TensorFlow 1.12 on Windows 10 ---- latest one  https://youtu.be/nZUxoHPFf4w",True
@hamzaelkasri31,2019-05-12T16:06:57Z,0,"Hi Everyone , I get this error when i want to generate Tfrecord ,Can you help me please ? : Traceback (most recent call last):   File ""generate_tfrecord.py"", line 100, in <module>     tf.app.run()   File "".............../.local/lib/python3.6/site-packages/tensorflow/python/platform/app.py"", line 125, in run     _sys.exit(main(argv))   File ""generate_tfrecord.py"", line 91, in main     tf_example = create_tf_example(group, path)   File ""generate_tfrecord.py"", line 80, in create_tf_example     'image/object/class/label': dataset_util.int64_list_feature(classes),   File ""................/Desktop/Algorithmes/models-master/research/object_detection/utils/dataset_util.py"", line 26, in int64_list_feature     return tf.train.Feature(int64_list=tf.train.Int64List(value=value)) TypeError: None has type NoneType, but expected one of: int, long",True
@KraatosPain,2019-05-12T02:42:21Z,1,"i was doing alright then i tried to intall the setup.py and got the following error: ""ModuleNotFoundError: No module named 'contextlib'"", then i found out that every command i try with python on CMD i get this error, never seen this, anyone know how to fix? thanks",True
@AlienAndrew51,2019-05-11T00:28:09Z,0,If your having trouble make sure you name your classes correctly in the CSV file.,True
@fenix20075,2019-05-05T05:07:53Z,0,"This is totally waste of time. Why we not create csv file when we identify the photo? You have wasted a half of video to tell us convent the xml into csv, I have spent a whole day to implement a node.js version application to saved the identification into xml. Now I have to spend another whole day convent the xml into csv...",True
@isabellatorresrevelo2576,2019-04-20T01:09:51Z,0,"I get an error when generating the tf_record. Goes like this. Please HELP     File ""generate_tfrecord.py"", line 11     python generate_tfrecord.py --csv_input=data/train_labels.csv --output_path=data/train.record --image_dir=images/train/                            ^ SyntaxError: invalid syntax   Don't understand why it is an invalid syntax :(",True
@javierb10,2019-03-28T04:40:11Z,1,somebody knows how to get the test record and the train record on windows?,True
@javierb10,2019-03-26T05:43:37Z,1,"sorry, i have followed all the steps, and I don't get any error but the code doesn't create the test_labels.csv and the other one, someone with the same problem??",True
@samandhindsa6009,2019-03-24T21:10:39Z,77,python generate_tfrecord.py --csv_input=data/test_labels.csv --output_path=data/test.record --image_dir=images/test/      (Note): Use the above command if u find randomaccess file error,True
@TheAkira2023,2019-03-13T12:45:57Z,10,NEVER change the directories of your images and xmls after creating them with the labelimage. Unless you wanna relabel everything again :),True
@JAMESDOOM22,2019-03-07T12:33:09Z,0,"When i did ""python3 generate_tfrecord.py --csv_input=data/test_labels.csv --output_path=data/test.record --image_dir=images/"" it says error in terminal but it generate .record file in both test and train, is it still ok to use these files for next step?",True
@shubhamnagalwade4642,2019-02-20T10:54:09Z,0,Please help me. when i was run the generate_tfrecord .py file i got error . error is  :- ModuleNotFoundError: No module named 'object_detection',True
@joeychukc,2019-02-03T04:12:38Z,0,"encoded_jpg = fid.read()     encoded_jpg_io = io.BytesIO(encoded_jpg)     image = Image.open(encoded_jpg_io)     width, height = image.size      filename = group.filename.encode('utf8')     image_format = b'jpg' According to the code, do we have to make sure all our pictures are in jpg?",True
@PieCheeseGuyGamingChannel,2019-01-10T02:43:12Z,2,I get this error when running tfrecords:  *raise KeyError(gpr) KeyError: 'filename'*,True
@PieCheeseGuyGamingChannel,2019-01-04T04:02:37Z,3,I get this error:  *tensorflow.python.framework.errors_impl.NotFoundError: Failed to create a NewWriteableFile:  : The system cannot find the path specified.  ; No such process*  How do I fix this? Please help.,True
@tejendherakhileshgrandhe4265,2018-12-21T12:17:14Z,0,"facing error with tf records generation unable to convert csv to tf records  File ""generate_tfrecord.py"", line 100, in <module>     tf.app.run()   File ""C:\Users\G.Akhilesh\Anaconda3\envs\tensorflow_cpu\lib\site-packages\tensorflow\python\platform\app.py"", line 125, in run     _sys.exit(main(argv))   File ""generate_tfrecord.py"", line 91, in main     tf_example = create_tf_example(group, path)   File ""generate_tfrecord.py"", line 46, in create_tf_example     encoded_jpg = fid.read()   File ""C:\Users\G.Akhilesh\Anaconda3\envs\tensorflow_cpu\lib\site-packages\tensorflow\python\lib\io\file_io.py"", line 125, in read     self._preread_check()   File ""C:\Users\G.Akhilesh\Anaconda3\envs\tensorflow_cpu\lib\site-packages\tensorflow\python\lib\io\file_io.py"", line 85, in _preread_check     compat.as_bytes(self.__name), 1024 * 512, status)   File ""C:\Users\G.Akhilesh\Anaconda3\envs\tensorflow_cpu\lib\site-packages\tensorflow\python\framework\errors_impl.py"", line 528, in __exit__     c_api.TF_GetCode(self.status.status)) tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: C:\tensorflow\scripts\preprocessing\images\40.jpg : The system cannot find the path specified. ; No such process  can any one help me in resolving this soon",True
@PaulBlxck,2018-12-18T14:35:31Z,2,"I get a  File ""generate_tfrecords.py"", line 134, in main     grouped = split(examples, 'filename')  keyError: 'filename'   Does anyone have a fix for that?",True
@faaizarashid9807,2018-12-18T04:36:57Z,0,"i am getting an error Attributeerror: module tensorflow has no attribute 'app'.  File ""generate_tfrecords.py"", line 23, in <module>",True
@divyamehta5282,2018-11-29T10:58:43Z,0,How you use PIL in ubuntu?? I tried but it showed that PIL is only for windows.,True
@aadishjoshi2525,2018-11-21T00:10:20Z,0,I got this error tensorflow.python.framework.errors_impl.NotFoundError: C:\Users\aadis\Anaconda3\lib\site-packages\tensorflow\contrib\coder\python\ops\_coder_ops.so not found,True
@abhinavrawat1460,2018-10-31T11:56:52Z,0,How to do this with video instead of images.?,True
@mohitmangal8378,2018-10-29T06:34:04Z,0,Thanks for this great tutorial. I have a doubt. From tensorflow object detection API gets original images? Does tfrecord also contains original images? Because in csv there is only image name and coordinates. From where will it get complete image for training ?,True
@oskarnatan,2018-10-19T22:07:09Z,0,[HELP] I run generate_tfrecord.py on it's directory and I get this error:   NewRandomAccessFile failed to Create/Open: D:\Tensorflow\workspace\training_demo\images\00000001.jpg : The system cannot find the file specified. ; No such file or directory  I already tried this:  python generate_tfrecord.py --label=face --csv_input=D:\Tensorflow\workspace\training_demo\annotations\train_labels.csv --output_path=D:\Tensorflow\workspace\training_demo\annotations\train.record --img_path=D:\Tensorflow\workspace\training_demo\images\train  and  python generate_tfrecord.py --label=face --csv_input=D:\Tensorflow\workspace\training_demo\annotations\train_labels.csv  --output_path=D:\Tensorflow\workspace\training_demo\annotations\train.record,True
@surbhiupadhyay53,2018-10-11T19:21:46Z,0,"hello , i am getting empty csv files.Can You please help me out.... why this is happening?",True
@mmajr,2018-10-08T21:04:03Z,1,Hi Sentdex! How did your code work if your images and XML are in the root of images folder and in your XML_to_csv.py point imagepath to images/train and images/test? Thanks!,True
@vashistnarayansingh5995,2018-10-04T19:07:54Z,0,Please make a video on yolo object detection,True
@emymimi7240,2018-09-24T15:40:24Z,0,thank you very much but the conversion xml_to_csv is it necessary ? why?,True
@mdazeemuddin1825,2018-09-18T07:45:49Z,0,"For anyone getting this error,  Traceback (most recent call last):   File ""generate_tfrecord.py"", line 97, in <module>     tf.app.run()   File ""C:\Users\User_name\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py"", line 125, in run     _sys.exit(main(argv))   File ""generate_tfrecord.py"", line 89, in main     tf_example = create_tf_example(group, path)   File ""generate_tfrecord.py"", line 78, in create_tf_example     'image/object/class/label': dataset_util.int64_list_feature(classes),   File ""C:\Users\User_name\Desktop\obj_fin1\object_detection\utils\dataset_util.py"", line 26, in int64_list_feature     return tf.train.Feature(int64_list=tf.train.Int64List(value=value)) TypeError: None has type NoneType, but expected one of: int, long  Try modifying generate_tfrecord.py in these lines if row_label == 'racoon':         return 1     else:         return 0   (Return '0' here and not None). I tried so harrd to get  this dammit!!! ;)",True
@garretthiggins6947,2018-09-14T18:35:32Z,0,I followed everything step by step but am getting:  tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: C:\Users\gahig\Desktop\object-detection\images\10.jpg : The system cannot find the path specified. ; No such process   Please help!!!,True
@justchill99902,2018-09-13T12:44:02Z,0,"I have a question here. Once we download the images, we label all of them and we split them into train and test directories as 90% and 10% of the images respectively.  But if the test data is not used for training, why do we label those images? This way if we pass these 'labeled' test images to our model(once the model has been trained), it will obviously know the where the bounding box is in the particular test image, won't it ?  But if you tell me that this 'test data' is actually the 'validation set', then I understand. Is that so? Because during training, the model learns from the training dataset(90%) and then validate the predictions using validation dataset(10%) (validation dataset is used to set the hyperparameters or to check during the training that the model doesn't memorize the features but generalizes them)  Is test dataset = validation dataset here? Please answer. Thanks Harrison!!",True
@mrexnx,2018-08-28T13:18:30Z,0,"@sentdex (or anyone), are the bounding boxes for these objects normalized by these scripts at all?",True
@justchill99902,2018-08-23T11:54:51Z,0,Thank you very much! :),True
@shanmugavelsugumar3529,2018-08-16T06:42:31Z,0,"File ""generate_tfrecord.py"", line 52, in create_tf_example     image = Image.open(encoded_jpg_io)   File ""/home/ubuntu/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/PIL/Image.py"", line 2622, in open     % (filename if filename else fp)) IOError: cannot identify image file <_io.BytesIO object at 0x7f8e874d4170> can anyone help solve this error",True
@neilfarricker8632,2018-08-14T23:54:18Z,3,"for anyone getting the error ""No such file or directory"" looking at the image files whilst running generate_tfrecord.py. The issue is to do with labelimg not attaching the file type on the filename element in the  xml output. you can get around this by altering the xml_to_csv.py script:     change  root.find('filename').text to root.find('filename').text+'.jpg'",True
@pawansj7881,2018-08-13T12:32:20Z,0,While generating tf record!! I'm getting errors like some images are not present in the directory,True
@ahmadmun7390,2018-08-13T12:22:05Z,1,"Hi  I am trying to run xml_to_csv.py but I have this errors (((  Traceback (most recent call last):   File ""xml_to_csv.py"", line 35, in <module>     main()   File ""xml_to_csv.py"", line 31, in main     xml_df = xml_to_csv(image_path)   File ""xml_to_csv.py"", line 17, in xml_to_csv     int(member[4][0].text), ValueError: invalid literal for int() with base 10: 'head ))) any help please??'",True
@shanmugavelsugumar3529,2018-08-10T14:07:09Z,0,tensorflow.python.framework.errors_impl.NotFoundError: /home/ubuntu/anaconda3/envs/tensorflow_p27/models/research/OD/images/train/IMAG1369; No such file or directory --- is the error i am getting when trying to run generate tf record.py. can someone help in this.  I followed @amit nair and alladdine idea still cant fix. thank you,True
@jm8069,2018-08-03T18:03:55Z,0,I made tfrecord file! Where is the codes that load my tfrecord file ? Anyone help?,True
@imenmkadem2878,2018-07-20T20:51:26Z,1,"Hey thank you for ur great job *__* , i have question if we have multiple classes ,we put all the images of # classes and their matching xml in the same directory ?? ?",True
@ANANTBARA,2018-07-12T15:48:58Z,0,"For people who are getting this error ""No module named 'object_detection'"", should run this ""tfrecord.py"" from the terminal on Linux (or set the appropriate python interpreter in spyder for the selected anaconda environment)",True
@uthiraamanikandan5378,2018-07-10T20:19:09Z,0,"Please help me solve this error:  row[class] : Hungry Jack Mashed Potatoes(11140871023) Classes Text : ['Hungry Jack Mashed Potatoes(11140871023)'] Hungry Jack Mashed Potatoes(11140871023) Classes Text : [1] Traceback (most recent call last):   File ""generate_tfrecord.py"", line 120, in <module>     tf.app.run()   File ""C:\Users\uthir\Anaconda3\envs\qwerty\lib\site-packages\tensorflow\python\platform\app.py"", line 126, in run     _sys.exit(main(argv))   File ""generate_tfrecord.py"", line 111, in main     tf_example = create_tf_example(group, path)   File ""generate_tfrecord.py"", line 91, in create_tf_example     'image/filename': dataset_util.bytes_feature(filename),   File ""C:\tensorflow12345\models\research\object_detection\utils\dataset_util.py"", line 30, in bytes_feature     return tf.train.Feature(bytes_list=tf.train.BytesList(value=[value])) TypeError: '00011140871023_A1C1_600_600.png' has type str, but expected one of: bytes",True
@rahulsingh_IITM,2018-07-10T12:06:17Z,0,"I am getting following error while running generate_tfrecords.py :- Traceback (most recent call last):   File ""generate_tfrecord.py"", line 16, in <module>     import pandas as pd   File ""/usr/lib/python3/dist-packages/pandas/__init__.py"", line 42, in <module>     import pandas.core.config_init   File ""/usr/lib/python3/dist-packages/pandas/core/config_init.py"", line 17, in <module>     from pandas.core.format import detect_console_encoding   File ""/usr/lib/python3/dist-packages/pandas/core/format.py"", line 10, in <module>     from pandas.core.index import Index, MultiIndex, _ensure_index   File ""/usr/lib/python3/dist-packages/pandas/core/index.py"", line 31, in <module>     from pandas.io.common import PerformanceWarning   File ""/usr/lib/python3/dist-packages/pandas/io/common.py"", line 68, in <module>     from boto.s3 import key   File ""/usr/lib/python3/dist-packages/boto/__init__.py"", line 1216, in <module>     boto.plugin.load_plugins(config)   File ""/usr/lib/python3/dist-packages/boto/plugin.py"", line 92, in load_plugins     for file in glob.glob(os.path.join(directory, '*.py')):   File ""/usr/lib/python3.5/posixpath.py"", line 89, in join     genericpath._check_arg_types('join', a, *p)   File ""/usr/lib/python3.5/genericpath.py"", line 143, in _check_arg_types     (funcname, s.__class__.__name__)) from None TypeError: join() argument must be str or bytes, not 'NoneType'",True
@catata4187,2018-07-05T10:27:00Z,0,Can someone upload his tfrecords please. For some reason I'm not able to create them. Thanks in advance.,True
@riyabanerjee2656,2018-07-02T22:13:46Z,0,"Hello,  Can I use the above program for Tensorflow CPU support?  When I run the code (video 6) I get the following error:  File ""/home/rao208//.local/lib/python3.5/site-packages/tensorflow/py thon/framework/errors_impl.py"", line 519, in __exist__ c_api.TF_GetCode(self.status.status)) tensorflow.python.framework.errors_impl.FailedPreconditionError: =; Is a directory  I do not know if this error is because I use Tensorflow CPU or some other reason",True
@amitnair92,2018-06-29T14:09:06Z,3,"i am getting error while trying to generate tf record  it says :   ""tensorflow.python.framework.errors_impl.NotFoundError: /home/dhruv/tf/object-detection/images/04PPRCCTVd_1517648262.jpg; No such file or directory""  but should not it look into images/train insterd of just images.   where am i going wrong.",True
@RahulYadav-gw8il,2018-06-28T09:21:06Z,0,how can save detected object please help me,True
@sriramgopal7189,2018-06-19T21:28:03Z,2,Could you pls explain more on the object detection error? give a solution with an example . For windows. I am struck in running that.,True
@salmaanakhtar6302,2018-06-16T13:33:57Z,0,"Hi,could anybody pls help me with this issue.I am running     python3 setup.py install and I am getting following error        python: can't open file 'setup.py': [Errno 2] No such file or directory",True
@adityasnehi6315,2018-06-12T05:53:49Z,0,"Help me plz Traceback (most recent call last):   File ""generate_tfrecord.py"", line 19, in <module>     from object_detection.utils import dataset_util ModuleNotFoundError: No module named 'object_detection' I m using ubuntu",True
@whiletruekill,2018-06-11T16:40:25Z,0,check out this implementation for converting videos to tfrecord files: https://github.com/ferreirafabio/video2tfrecord,True
@1chinthaka,2018-06-07T04:49:42Z,1,This tutorial is great. Superb. But your laughing sound freaks me out. You laugh in a heuristic way which is scary. Just kidding,True
@charimuvilla8693,2018-06-06T17:03:17Z,0,Nice tutorial! So can I add some unlabeled photos of objects I don't want to track to give the program more info on what to track? For example if I want to track women in the picture (example I came up with) should I add some unlabeled men too?,True
@avinashkachare2482,2018-05-24T08:53:25Z,28,12.30 setup.py is in research folder,True
@paatz04,2018-05-20T17:29:41Z,0,Does it matter how large the images are used to train/test ? Thanks!,True
@denis14594,2018-05-07T20:58:15Z,0,I have a question: Is the path of the images important? I have used sloth to label images and than created a script to convert from json to xml. To the xml i put the path of the images but it's not the final one. Should I put the final path in order to work? P.s. Great video man.,True
@Ramiphylo,2018-04-29T12:08:23Z,13,"Please help, when generating the tf_records: tensorflow.python.framework.errors_impl.NotFoundError: ; No such file or directory",True
@dpacmanh,2018-04-13T11:36:44Z,4,For anyone on windows having problem exporting the: -  # From tensorflow/models/ export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim  Run instead: set PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim,True
@osumanaaa9982,2018-04-11T04:52:33Z,0,"Thanks again for these awesome tutorials. I actually followed this whole one to detect and track objects on videos I recorded (same background and same subject), but the boxes would not appear at the end. I used Vitbat to label (since I used videos) and I just realized that, unlike the tool you used, vitbat gives labels as float not as int. Do you think that could explain what went wrong with my training of the model ?",True
@maykhal93,2018-04-08T18:45:06Z,0,+sentdex can you give me the generateur of XML files from images and that's help me so much and thenk you,True
@vibhutirastogi45,2018-03-17T15:14:07Z,0,"Hey after running generate_tfrecords I am getting this error, can you please help me out? Traceback (most recent call last):   File ""generate_tfrecord.py"", line 104, in <module>     tf.app.run()   File ""/home/16mcmt36/anaconda3/envs/api_env/lib/python3.6/site-packages/tensorflow/python/platform/app.py"", line 48, in run     _sys.exit(main(_sys.argv[:1] + flags_passthrough))   File ""generate_tfrecord.py"", line 92, in main     examples = pd.read_csv(FLAGS.csv_input)   File ""/home/16mcmt36/anaconda3/envs/api_env/lib/python3.6/site-packages/pandas/io/parsers.py"", line 709, in parser_f     return _read(filepath_or_buffer, kwds)   File ""/home/16mcmt36/anaconda3/envs/api_env/lib/python3.6/site-packages/pandas/io/parsers.py"", line 455, in _read     data = parser.read(nrows)   File ""/home/16mcmt36/anaconda3/envs/api_env/lib/python3.6/site-packages/pandas/io/parsers.py"", line 1069, in read     ret = self._engine.read(nrows)   File ""/home/16mcmt36/anaconda3/envs/api_env/lib/python3.6/site-packages/pandas/io/parsers.py"", line 1839, in read     data = self._reader.read(nrows)   File ""pandas/_libs/parsers.pyx"", line 902, in pandas._libs.parsers.TextReader.read   File ""pandas/_libs/parsers.pyx"", line 924, in pandas._libs.parsers.TextReader._read_low_memory   File ""pandas/_libs/parsers.pyx"", line 978, in pandas._libs.parsers.TextReader._read_rows   File ""pandas/_libs/parsers.pyx"", line 965, in pandas._libs.parsers.TextReader._tokenize_rows   File ""pandas/_libs/parsers.pyx"", line 2208, in pandas._libs.parsers.raise_parser_error pandas.errors.ParserError: Error tokenizing data. C error: Expected 8 fields in line 188, saw 9",True
@duanoor1553,2018-03-03T06:54:38Z,0,"Hi I have successfully created tFrecords with my old dataset. But for my new dataset I got this error while generating tfRecord. And Im working on one class. Please help me  C:\Users\OMEN\Desktop\object-detection>python generate_tfrecord.py --csv_input=data/train_labels.csv --output_path=data/train.record Traceback (most recent call last):   File ""generate_tfrecord.py"", line 99, in <module>     tf.app.run()   File ""C:\Users\OMEN\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\platform\app.py"", line 124, in run     _sys.exit(main(argv))   File ""generate_tfrecord.py"", line 90, in main     tf_example = create_tf_example(group, path)   File ""generate_tfrecord.py"", line 79, in create_tf_example     'image/object/class/label': dataset_util.int64_list_feature(classes),   File ""F:\Project\models\research\object_detection\utils\dataset_util.py"", line 26, in int64_list_feature     return tf.train.Feature(int64_list=tf.train.Int64List(value=value))   File ""C:\Users\OMEN\AppData\Local\Programs\Python\Python36\lib\site-packages\google\protobuf\internal\python_message.py"", line 510, in init     copy.extend(field_value)   File ""C:\Users\OMEN\AppData\Local\Programs\Python\Python36\lib\site-packages\google\protobuf\internal\containers.py"", line 275, in extend     new_values = [self._type_checker.CheckValue(elem) for elem in elem_seq_iter]   File ""C:\Users\OMEN\AppData\Local\Programs\Python\Python36\lib\site-packages\google\protobuf\internal\containers.py"", line 275, in <listcomp>     new_values = [self._type_checker.CheckValue(elem) for elem in elem_seq_iter]   File ""C:\Users\OMEN\AppData\Local\Programs\Python\Python36\lib\site-packages\google\protobuf\internal\type_checkers.py"", line 133, in CheckValue     raise TypeError(message) TypeError: None has type <class 'NoneType'>, but expected one of: (<class 'int'>,)",True
@mohithdamarapati5717,2018-02-19T06:34:53Z,0,"Hey Sentdex,  I have a problem while generating the TF Records as I am using Python 2.  I installed setup.py using python2.  But while I am trying to generate TF Records, I get an import error that object_detection.utils is not present. I have everything in python2. Can you help me to solve this problem? Thank You",True
@jakubbator4699,2018-02-18T19:33:36Z,0,"I am trying to train my custom object by using tensorflow, however, when I run command it shows an error with protobuf:  File ""/usr/local/lib/python3.5/dist-packages/google/protobuf/text_format.py"", line 1152, in ConsumeIdentifierOrNumber      raise self.ParseError('Expected identifier or number, got %s.' % result)   google.protobuf.text_format.ParseError: 235:1 : Expected identifier or number, got <.   I am using following command to run train.py: python3 train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/ssd_mobilenet_v1_pets.config",True
@armanamedi3386,2018-02-16T00:33:26Z,0,"Hey sentdex, this is kind of old fashion of object detection, can you please make some video tutorials by using  Convolutional Neural networks, would be grateful",True
@pranavjoshi5808,2018-02-11T19:34:58Z,0,"(base) H:\Projects\object-detection>python generate_tfrecord.py --csv_input=data/train_labels.csv  --output_path=train.record  Traceback (most recent call last):   File ""generate_tfrecord.py"", line 98, in <module>     tf.app.run()   File ""H:\Anaconda\lib\site-packages\tensorflow\python\platform\app.py"", line 48, in run     _sys.exit(main(_sys.argv[:1] + flags_passthrough))   File ""generate_tfrecord.py"", line 89, in main     tf_example = create_tf_example(group, path)   File ""generate_tfrecord.py"", line 78, in create_tf_example     'image/object/class/label': dataset_util.int64_list_feature(classes),   File ""H:\Anaconda\lib\site-packages\object_detection-0.1-py3.6.egg\object_detection\utils\dataset_util.py"", line 26, in int64_list_feature   File ""H:\Anaconda\lib\site-packages\google\protobuf\internal\python_message.py"", line 510, in init     copy.extend(field_value)   File ""H:\Anaconda\lib\site-packages\google\protobuf\internal\containers.py"", line 275, in extend     new_values = [self._type_checker.CheckValue(elem) for elem in elem_seq_iter]   File ""H:\Anaconda\lib\site-packages\google\protobuf\internal\containers.py"", line 275, in <listcomp>     new_values = [self._type_checker.CheckValue(elem) for elem in elem_seq_iter]   File ""H:\Anaconda\lib\site-packages\google\protobuf\internal\type_checkers.py"", line 133, in CheckValue     raise TypeError(message) TypeError: None has type <class 'NoneType'>, but expected one of: (<class 'int'>,)  This is the error i am getting.Trying to hunt this error since 3 days.Please help me out guys.",True
@utilitiesapp6715,2018-02-09T07:02:46Z,0,wow great job Mr.sentdex. And thanks alot.Only your tutorial is trusted. Others are like copied version...,True
@waleedhamdy6175,2018-02-08T16:47:03Z,0,"I want the same commit of models, you were working with",True
@beshprakash1261,2018-01-31T08:42:16Z,0,"I got this error in generate_tfrecord.py. So, How can I solve this problem. Traceback (most recent call last):   File ""generate_tfrecord.py"", line 20, in <module>     from object_detection.utils import dataset_util ImportError: No module named object_detection.utils",True
@JuJoVij,2018-01-30T04:08:32Z,0,"Hello can anybody help me ? I followed this tutorial since start and now I am getting an error in setup.py installation. I am using Anaconda but it shows me an error when I run ""sudo python setup.py install"" telling ""No module named setuptools"". But in conda list setuptools exists.",True
@DrKhan-hd4cd,2018-01-26T17:40:12Z,0,"Guys, i am getting this error-->tensorflow.python.framework.errors_impl.NotFoundError: training/ssd_mobilenet_v1_pets.config; No such file or directory  and i can pay you to fix it for me",True
@nikhilshetty8698,2018-01-25T16:00:31Z,0,"Traceback (most recent call last):   File ""generate_tfrecord.py"", line 99, in <module>     tf.app.run()   File ""/Users/nikhil/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py"", line 48, in run     _sys.exit(main(_sys.argv[:1] + flags_passthrough))   File ""generate_tfrecord.py"", line 90, in main     tf_example = create_tf_example(group, path)   File ""generate_tfrecord.py"", line 47, in create_tf_example     image = Image.open(encoded_jpg_io)   File ""/Users/nikhil/anaconda3/lib/python3.6/site-packages/PIL/Image.py"", line 2519, in open     % (filename if filename else fp)) OSError: cannot identify image file <_io.BytesIO object at 0x115f22bf8>",True
@faheemirfan6598,2018-01-20T15:21:50Z,4,I am getting empty files after running xml_to_csv.py.? any solution,True
@faheemirfan6598,2018-01-20T13:58:59Z,0,facing a problem in paperspace. I upgraded tensorflow to 1.4.1 but when i run jupyter notebook and object detection example. It gives me error tensorflow version must be 1.4.X or later. When i open terminal and type python and import tensor flow and check version it gives me 1.4.1. Can you please solve my issue,True
@sunghwancho9574,2018-01-10T06:07:26Z,0,"Thank you for your guide. I have a problem. i try install 'sudo python3 setup.pu install' but it  has a error. ( Traceback (most recent call last): File ""setup.py"" , line 3, in <module> from setuptools import find_packages | ModuleNotFoundError :No module named 'setuptools' )  I don't know why did not install...  My python --version => Python 3.6.1 :: Anaconda custom(64-bit) / Ubuntu 16.04",True
@arpitsrivastava8431,2017-12-31T09:51:07Z,0,"If we got multiple objects we will apply return 1,2,3,.... so on.or just return 1",True
@musiclover470,2017-12-29T19:30:48Z,1,how  do you install the setup.py file on a windows 10 ??,True
@ShahidKhan-my1gi,2017-12-26T07:44:27Z,0,"hi sentdex, Thankyou for such a nice tutorial.It is a great tutorial :)  it helped me learn a lot on how to build object detection model using tensorflow api. I appreciate your effort in sharing your knowledge.  could you please give some assistance on how to build a web service on this model. can you enlighten us in creating web service for this model where i could provide input image and get the results by detecting objects?",True
@yegorkolodyazhniy6261,2017-12-20T11:46:17Z,0,My output csv files have only column names. Please help,True
@prasaddalavi9683,2017-12-18T05:45:13Z,0,Can you please help me with my silly question. How did you open python file with atom using open with options. I tried many solutions but could not get it. I have tried it by moving atom.desktop file to ~local/.............,True
@aboodkh6837,2017-12-13T07:26:43Z,0,"Hello guys! I am facing theses Errors     File ""generate_tfrecord.py"", line 118, in <module>     tf.app.run()   File ""C:\Users\Abood\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py"", line 48, in run     _sys.exit(main(_sys.argv[:1] + flags_passthrough))   File ""generate_tfrecord.py"", line 109, in main     tf_example = create_tf_example(group, path)   File ""generate_tfrecord.py"", line 83, in create_tf_example     classes_text.append(row['class'].encode('utf8')) AttributeError: 'int' object has no attribute 'encode'",True
@TamNguyen-rf2bu,2017-12-11T18:34:21Z,2,"Can someone answer this quickly please? I am able to generate the csv files but there is nothing in it except this line: filename,width,height,class,xmin,ymin,xmax,ymax. Is someone else getting the same error? And File ""generate_tfrecord.py"", line 20, in <module>     from object_detection.utils import dataset_util ImportError: No module named 'object_detection' Thanks all!!",True
@afshananwarali9462,2017-12-11T09:19:04Z,0,You do amazing work! Thanks alot sentdex. I have learnt alot from your tutorials. :D,True
@unidenz2010,2017-12-07T04:59:37Z,1,"Can someone answer this quickly please? I am able to generate the csv files but there is nothing in it except this line: filename,width,height,class,xmin,ymin,xmax,ymax. Is someone else getting the same error?",True
@kaushikprakashrobotics,2017-12-04T22:50:28Z,0,Can you use webcam for real time object recognition on paperspace?,True
@davidgaylard148,2017-11-26T04:54:51Z,2,"Hey guys, any help with running this on anaconda? I'm getting the error ""No module named 'object_detection'"" when trying to run the script in spyder. I'm assuming that's because the script cant run the line 'from object_detection.utils import dataset_util' because it doesn't know where that is, any help? windows by the way.",True
@whiletruekill,2017-11-25T16:36:53Z,1,"if you want to create tfrecords from raw video data, this code helps you: https://github.com/ferreirafabio/video2tfrecords",True
@kamilakin6866,2017-11-23T22:23:24Z,0,"Hello everybody.First of all,thank you Sentdex! You know what.Thank you thousands of time! I am using windows10/Anaconda/JupyterNotebook and when I try to run(14:36 in video)  ""python3 generate_tfrecord.py --csv_input=data/train_labels.csv  --output_path=data/train.record"" code on my cmd.  I got this error code""'python3' is not recognized as an internal or external command, operable program or batch file"". And when I change it to --python3-- to --python-- I got this error "" File ""generate_tfrecord.py"", line 1     Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)] on win32              ^ SyntaxError: invalid syntax"" Does anyone have an idea how to fix it? Cheers",True
@mohamedusuf1,2017-11-23T06:17:21Z,1,"iam getting error while generating tfrecords? frecord.py --csv_input=data/train_labels.csv  --output_path=data/train.record Traceback (most recent call last):   File ""generate_tfrecord.py"", line 99, in <module>     tf.app.run()   File ""/home/usuf/tensoeve/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py"", line 48, in run     _sys.exit(main(_sys.argv[:1] + flags_passthrough))   File ""generate_tfrecord.py"", line 90, in main     tf_example = create_tf_example(group, path)   File ""generate_tfrecord.py"", line 79, in create_tf_example     'image/object/class/label': dataset_util.int64_list_feature(classes),   File ""/home/usuf/Desktop/models/research/object_detection/utils/dataset_util.py"", line 26, in int64_list_feature     return tf.train.Feature(int64_list=tf.train.Int64List(value=value)) TypeError: None has type NoneType, but expected one of: int, long  any solution for this plz?",True
@arun_das_k,2017-11-08T12:41:03Z,0,Should I need to resize image before labelling ??,True
@karkinissan,2017-11-02T10:08:13Z,0,"Bloody hell, the provided create_pascal_tf_record.py in the object_detection git folder is a nightmare to run. Designed for a specific ""aeroplane"" dataset. Thank you for providing Dat Tran's code. His is much better and generic.",True
@karkinissan,2017-11-02T09:17:07Z,0,Does rotating the images and changing this like brightness and saturation help artificially inflate the dataset? Or will it have no effect at all?,True
@MrGramatix,2017-11-01T19:56:52Z,1,"Hi, thanks for this awesome tutorial sentdex, I want to know how to install Object_Detection in Anaconda?",True
@renukanale8670,2017-10-24T08:47:45Z,0,"when I used a genrate_tfrecord script for my dataset getting following error.  Traceback (most recent call last):   File ""generate_tfrecord.py"", line 100, in <module>     tf.app.run()   File ""C:\Users\Sanjay_pc\python35\lib\site-packages\tensorflow\python\platform \app.py"", line 48, in run     _sys.exit(main(_sys.argv[:1] + flags_passthrough))   File ""generate_tfrecord.py"", line 91, in main     tf_example = create_tf_example(group, path)   File ""generate_tfrecord.py"", line 80, in create_tf_example     'image/object/class/label': dataset_util.int64_list_feature(classes),   File ""C:\Users\Sanjay_pc\python35\pythonprograming\Object_Detection\dataset_ut il.py"", line 9, in int64_list_feature     return tf.train.Feature(int64_list=tf.train.Int64List(value=value))   File ""C:\Users\Sanjay_pc\python35\lib\site-packages\google\protobuf\internal\p ython_message.py"", line 509, in init     copy.extend(field_value)   File ""C:\Users\Sanjay_pc\python35\lib\site-packages\google\protobuf\internal\c ontainers.py"", line 275, in extend     new_values = [self._type_checker.CheckValue(elem) for elem in elem_seq_iter]    File ""C:\Users\Sanjay_pc\python35\lib\site-packages\google\protobuf\internal\c ontainers.py"", line 275, in <listcomp>     new_values = [self._type_checker.CheckValue(elem) for elem in elem_seq_iter]    File ""C:\Users\Sanjay_pc\python35\lib\site-packages\google\protobuf\internal\t ype_checkers.py"", line 133, in CheckValue     raise TypeError(message) TypeError: None has type <class 'NoneType'>, but expected one of: (<class 'int'> ,)",True
@renukanale8670,2017-10-24T08:44:53Z,2,"Hello, Sentdex thank you for a nice tutorial.  I have one question can I used same script (genrate_tfrecord) if images contain more than one box and one than one class. If not can you suggest me where I have to make changes?  Thank you",True
@criscanto7040,2017-10-22T20:31:16Z,0,"Sentdex awsome videos!! thanks for helping to clarify  all steps in the way.. any way Im having some questions related to training more than one class. Do all images and xml representations have to be in the same folder, or do i have to create single folder for each class???  Also did this work for you when trying to train multiple classes?  # TO-DO replace this with label map def class_text_to_int(row_label):     if row_label == 'Label1':         return 1   if row_label == 'label2'     else:         None any advice will be of much help, thanks in advance to anyone and Sentdex!!!",True
@amaresh219,2017-10-21T18:04:36Z,0,"I have encountered error after running following command. Anyone just help me out please!   amaresh@amaresh-HP-Pavilion-Notebook:~/blindspot_adas$ python3 generate_tfrecord.py --csv_input=data/train_labels.csv  --output_path=data/train.record Traceback (most recent call last):   File ""generate_tfrecord.py"", line 99, in <module>     tf.app.run()   File ""/home/amaresh/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py"", line 48, in run     _sys.exit(main(_sys.argv[:1] + flags_passthrough))   File ""generate_tfrecord.py"", line 90, in main     tf_example = create_tf_example(group, path)   File ""generate_tfrecord.py"", line 45, in create_tf_example     encoded_jpg = fid.read()   File ""/home/amaresh/anaconda3/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py"", line 118, in read     self._preread_check()   File ""/home/amaresh/anaconda3/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py"", line 78, in _preread_check     compat.as_bytes(self.__name), 1024 * 512, status)   File ""/home/amaresh/anaconda3/lib/python3.6/contextlib.py"", line 89, in __exit__     next(self.gen)   File ""/home/amaresh/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py"", line 466, in raise_exception_on_not_ok_status     pywrap_tensorflow.TF_GetCode(status)) tensorflow.python.framework.errors_impl.NotFoundError: /home/amaresh/blindspot_adas/images/1-500x500.jpg",True
@whiletruekill,2017-10-19T07:10:53Z,0,"if you're interested in converting raw video to tf records, check out the code under the following repo: https://github.com/ferreirafabio/video2tfrecords",True
@TalBizi,2017-10-18T15:01:06Z,0,"Hey guys,  Could someone please share where the main directories and files should be saved relative to each other? (mainly I think- models, object-detection, generate_tfrecord.py, and the tensorflow installation)  Each time I manage to fix a certain path that the code cannot find another one appears... I've been on this for hours. Thanks a lot",True
@juancarlosorozco9122,2017-10-17T23:25:42Z,0,"hello, what were the steps of the 12th minute?",True
@rishabhanand1281,2017-10-14T12:42:37Z,0,Hey Harrison! Was following this tutorial when I got this error when downloading the setup.py file: /usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/Resources/Python.app/Contents/MacOS/Python: can't open file 'setup.py': [Errno 2] No such file or directory   How can I progress from here?,True
@abhishekmgm78,2017-10-12T17:27:24Z,3,"File ""generate_tfrecord.py"", line 20, in <module>     from object_detection.utils import dataset_util ImportError: No module named 'object_detection'    can anyone help??",True
@susansheehan1455,2017-09-20T17:45:41Z,0,"Hi,  Can you talk a little about the tfRecords?  I have objects identified off Images from another program  (they are roughly circular) ideally I want to be able to train tensorflow to detect them and export the outlines for further downstream analysis.   My other program only exports the midpoint X and Y of the region of interest.   I can get those values into .csv  I cannot find a good description of what is needed as far as information for the tfRecords.  I see that you had min and max in both the X and Y direction are these required?",True
@luckysameer3502,2017-09-20T10:54:26Z,0,How that XML are generated During Image labeling those XML annotations are prepared automatically or did we need to prepare them.Help me out please.As of now im working with your dataset sentex,True
@hunt4u81,2017-09-15T07:54:09Z,2,"python generate_tfrecord.py --csv_input=data/train_labels.csv --output_path=data/train.record python: can't open file 'generate_tfrecord.py': [Errno 2] No such file or directory uguess@linux-e5od:~/PycharmProjects> cd tensorflow/ uguess@linux-e5od:~/PycharmProjects/tensorflow> python generate_tfrecord.py --csv_input=data/train_labels.csv --output_path=data/train.record Traceback (most recent call last):   File ""generate_tfrecord.py"", line 97, in <module>     tf.app.run()    File ""/home/uguess/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py"", line 48, in run     _sys.exit(main(_sys.argv[:1] + flags_passthrough))   File ""generate_tfrecord.py"", line 88, in main     tf_example = create_tf_example(group, path)   File ""generate_tfrecord.py"", line 44, in create_tf_example     encoded_jpg = fid.read()   File ""/home/uguess/.local/lib/python2.7/site-packages/tensorflow/python/lib/io/file_io.py"", line 118, in read     self._preread_check()   File ""/home/uguess/.local/lib/python2.7/site-packages/tensorflow/python/lib/io/file_io.py"", line 78, in _preread_check     compat.as_bytes(self.__name), 1024 * 512, status)   File ""/usr/lib64/python2.7/contextlib.py"", line 24, in __exit__     self.gen.next()   File ""/home/uguess/.local/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py"", line 466, in raise_exception_on_not_ok_status     pywrap_tensorflow.TF_GetCode(status)) tensorflow.python.framework.errors_impl.NotFoundError: /home/uguess/PycharmProjects/tensorflow/images/img7.jpg",True
@janefan1227,2017-09-15T01:13:56Z,0,"I was using labelimg v.1.2 prebuilt binary for windows (https://tzutalin.github.io/labelImg/ ). It seems to generate the xml differently. In particular the <filename> tag contains only the filename, no extension. This caused generate_tfrecord to fail because it didn't find the path to the image. I changed root.find('filename') to root.find('path') in xml_to_csv. Hopes this helps someone. Only issue is that path is a absolute path so you'll probably need to re-run the scripts if you move the folder",True
@ameykale603,2017-09-12T16:18:56Z,3,"I am getting the following error. Can you please resolve this SENTDEX??  Traceback (most recent call last):   File ""generate_record.py"", line 99, in <module>     tf.app.run()   File ""/home/ameya/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py"", line 48, in run     _sys.exit(main(_sys.argv[:1] + flags_passthrough))   File ""generate_record.py"", line 90, in main     tf_example = create_tf_example(group, path)   File ""generate_record.py"", line 79, in create_tf_example     'image/object/class/label': dataset_util.int64_list_feature(classes),   File ""/home/ameya/anaconda3/lib/python3.6/site-packages/object_detection-0.1-py3.6.egg/object_detection/utils/dataset_util.py"", line 26, in int64_list_feature TypeError: None has type NoneType, but expected one of: int, long",True
@sandyleon6205,2017-09-10T16:32:42Z,0,Is it possible to track objects on screen? So not using the webcam but rather a video directly on my computer?,True
@RafaelLehmkuhl93,2017-09-08T23:32:09Z,0,Hi sentdex! Nice video again! One question: I'm having trouble generating the TFrecords. I used the same commit as yours and my data seens to be on the same format. Did you see something like that: https://github.com/datitran/raccoon_dataset/issues/16 ?,True
@mattmullin5,2017-09-07T22:06:17Z,0,"Hey I am having trouble with updating to protoc-3.4.0 on the paperspace ML virtual machine. I have run the ""protoc object_detection/protos/*.proto --python_out=."" command in the models folder and have tried the process several times with no success and every time I run ""protoc --verison"" it still says I am running 2.5. Any ideas what to do? thanks for the videos and the $10 credit!",True
@saeedsalimian1812,2017-09-07T16:29:25Z,0,"turn off the TV , we might run out of electricity  :|",True
@MrSimon2935,2017-09-06T15:55:56Z,0,I don't what to do with the protoc-3.4.0 in windows where to extract it ?,True
@fizzzenith7992,2017-09-03T23:53:59Z,3,"I'm getting this error when converting csv to tfrecord.... Please help   Traceback (most recent call last):   File ""generate_tfrecord.py"", line 105, in <module>     tf.app.run()   File ""C:\My_Items\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\platform\app.py"", line 48, in run     _sys.exit(main(_sys.argv[:1] + flags_passthrough))   File ""generate_tfrecord.py"", line 94, in main     grouped = split(examples, 'filename')   File ""generate_tfrecord.py"", line 45, in split     gb = df.groupby(group)   File ""C:\My_Items\Anaconda3\envs\tensorflow\lib\site-packages\pandas\core\generic.py"", line 4416, in groupby     **kwargs)   File ""C:\My_Items\Anaconda3\envs\tensorflow\lib\site-packages\pandas\core\groupby.py"", line 1699, in groupby     return klass(obj, by, **kwds)   File ""C:\My_Items\Anaconda3\envs\tensorflow\lib\site-packages\pandas\core\groupby.py"", line 392, in __init__     mutated=self.mutated)   File ""C:\My_Items\Anaconda3\envs\tensorflow\lib\site-packages\pandas\core\groupby.py"", line 2690, in _get_grouper     raise KeyError(gpr) KeyError: 'filename'",True
@jayshah4016,2017-09-03T07:51:41Z,3,Hey I did run SET PATH=%PATH%;%cd%;%cd%\slim but still I get an error ImportError: No module named 'deployment',True
@jayshah4016,2017-09-03T05:49:48Z,0,You forgot to put the labeled images and their xmls in annotations folder in your text based tutorial,True
@lizardy2867,2017-08-31T02:33:45Z,1,"Sentdex, do you know a solution to this error in generate_tfrecord?: TypeError: None has type <class 'NoneType'>, but expected one of: (<class 'int'>,)",True
@KellenChase,2017-08-30T04:15:41Z,1,never thought id see you use atom... makes me smile.  :),True
@abdennacerlachiheb319,2017-08-26T13:32:48Z,0,"Hi, great tutorial, I'm wondering what software you are using to record screen in ubuntu?",True
@boredgaming91,2017-08-26T06:46:20Z,1,whatever you did on linux will work on windows 10..??? and another question after adding a basic amount of macncheese images is it possible that the model learns that it is a new image and it doesnt have a image like that and stores it after seeing a new macncheese image which has a accuracy of say > 97%. It will make things far more easier if say i add a base of 100 images and the keeps on adding other images to a user set limit,True
@DUANEYAISER,2017-08-26T04:16:24Z,0,Came here for the mac & cheese,True
@kx1235,2017-08-26T00:16:38Z,0,"could you teach us how to count the number of say ""person"" objects in a frame?",True
@firespark804,2017-08-25T18:11:11Z,0,How do i get labelimg on Windows 10 ? git clone url does not work,True
@vikaskyatannawar8417,2017-08-25T15:33:51Z,0,i havent started this series... want to learn tensor flow for a project which i have in mind... do i need to learn python2 or python3 for it..i did not do much coding in python so will learn in a couple of days again to refresh everything...but first thing which i noticed is python3 introduced....so which should i learn as pre-requisite.,True
@ShayanSSadar,2017-08-25T14:46:06Z,0,"Sir I have been following your channel and you're great. I'm doing a project on lip reading and generating text, how should I go about it?",True
@alpeshvasani8626,2017-08-25T14:11:15Z,0,great job sir.. you are dammm good. i want to make an real time(webcam) face detection and using tensorflow...can you please help me out which tutorial should i follow to do so.. thank you Sir.,True
@Oohenry1,2017-08-25T14:07:46Z,1,ummmmmm yes... that's the good stuff...,True
