author,updated_at,like_count,text,public
@shimulvillagefunction8411,2021-11-04T05:23:49Z,0,"Hi Sentdex, when I am running the code in Kaggle, I found the error ""ModuleNotFoundError: No module named 'tflearn'"", plz what to do?",True
@ayarisalim5760,2021-04-06T21:18:13Z,0,"HELLO, just i want to know how to change this part of code : /* import matplotlib.pyplot as plt  # if you need to create the data: #test_data = process_test_data() # if you already have some saved: test_data = np.load('test_data.npy')  fig=plt.figure()  for num,data in enumerate(test_data[:12]):     # cat: [1,0]     # dog: [0,1]          img_num = data[1]     img_data = data[0]          y = fig.add_subplot(3,4,num+1)     orig = img_data     data = img_data.reshape(IMG_SIZE,IMG_SIZE,1)     #model_out = model.predict([data])[0]     model_out = model.predict([data])[0]          if np.argmax(model_out) == 1: str_label='Dog'     else: str_label='Cat'              y.imshow(orig,cmap='gray')     plt.title(str_label)     y.axes.get_xaxis().set_visible(False)     y.axes.get_yaxis().set_visible(False) plt.show() */ when i have for exemple dog , cat , bird ; i mean more than 3. And how could i test ur code on image like this :  https://metro.co.uk/wp-content/uploads/2019/12/PRI_104564221.jpg?quality=90&strip=all",True
@WhiteKnightLord,2020-12-05T16:57:21Z,0,"Model Fitting error: 1. if u r getting something like train_1/x::: pass dtype wherever u r making np.array() 2. if u r getting like target_1/y use tf.compat.v1.reset_default_graph() just after the wherever u have imported tensorflow. Some points which I faced and their solution: 1. if u r working on newer numpy, always pass dtype = object in the parameter of np.array() 2. I am using tensorflow 2.xx    tflearn 0.05(something like this). 3. If u have version compatibility issues with tf2.0.0   I made a virtual env using conda then used pip to install latest of everything.  I don't know why these things worked but these worked for me .",True
@pankajuprety9216,2020-11-26T12:37:30Z,0,"can you please explain why we use this code:-  convnet = fully_connected(convnet, 1024, activation='relu').. i guess this is use to convert image into arrays but why do we use it twice? and why are we giving value 1024",True
@inv1siblecat,2020-09-17T00:12:34Z,0,"when i try to run it i get this error:     from tensorflow.python.compiler.tensorrt import trt_convert as tf ImportError: cannot import name 'trt_convert' from 'tensorflow.python.compiler.tensorrt' (C:\Users\shiel\PycharmProjects\dogvrscat\venv\lib\site-packages\tensorflow\python\compiler\tensorrt\__init__.py)",True
@SergKiev87,2020-07-28T22:50:49Z,1,I know that you can read what you just wrote. But you could've at least explain what function does what. Instead you are just mumbling.,True
@ZikyFranky,2020-06-18T20:30:18Z,10,"if you get this error InvalidArgumentError: You must feed a value for placeholder tensor 'input_1/X' with dtype float and shape [?,50,50,1] import tensorflow as tf tf.reset_default_graph() This Solved it for me.",True
@akshatjain3938,2020-04-26T06:18:57Z,1,"It gives me the following error what should I do?   Invalid argument: You must feed a value for placeholder tensor 'targets_1/Y' with dtype float and shape [?,2] 	 [[{{node targets_1/Y}}]] 	 [[Crossentropy_1/Mean/moving_avg/read/_49]]   (1) Invalid argument: You must feed a value for placeholder tensor 'targets_1/Y' with dtype float and shape [?,2] 	 [[{{node targets_1/Y}}]]",True
@nishantmittalblog,2020-03-12T10:40:50Z,0,"I am getting error in the last line  --------------------------------- Run id: dogsvscats-0.001-2conv-basic.model Log directory: log/ --------------------------------- Training samples: 0 Validation samples: 1 -- Exception in thread Thread-16: Traceback (most recent call last):   File ""/usr/lib/python3.6/threading.py"", line 916, in _bootstrap_inner     self.run()   File ""/usr/lib/python3.6/threading.py"", line 864, in run     self._target(*self._args, **self._kwargs)   File ""/usr/local/lib/python3.6/dist-packages/tflearn/data_flow.py"", line 201, in fill_batch_ids_queue     ids = self.next_batch_ids()   File ""/usr/local/lib/python3.6/dist-packages/tflearn/data_flow.py"", line 215, in next_batch_ids     batch_start, batch_end = self.batches[self.batch_index] IndexError: list index out of range   Please help.",True
@vijayzaware7621,2020-03-07T06:07:43Z,0,"Implenting this on colab, it is not reading data ""file not found error"" is their a way out of this  One i know is to upload data on google drive",True
@santosh0236,2020-02-29T04:53:19Z,1,"Hi Sentdex, Please confirm your version Python and Tflearn. Because I'm not able to import the library (tflearn). So my next step is pending.",True
@soufianeerraji9030,2019-12-25T23:22:12Z,1,i got the error : ModuleNotFoundError: No module named 'tensorflow.contrib' i knew it has been removed from veron 2.0 and when i downgrade to 1.14 of tf  i get  this error no module named 'tensorflow.python.estimator' . Any solution/suggestion. ?,True
@keremtek3319,2019-12-17T07:42:55Z,0,"I got error below in model.fit part ; """"""You must feed a value for placeholder tensor 'targets_1/Y' with dtype float and shape [?,2]""""""   Solved by adding the    tf.reset_default_graph()   , before creating graph.",True
@raizadimapilisborreo9642,2019-10-10T19:01:00Z,2,I got an error: The name tf.summary.merge is deprecated. Please use tf.compat.v1.summary.merge instead. Kindly help thanks.,True
@princeps656,2019-09-22T12:00:55Z,0,why we reshape for X and Y,True
@Kyuboyo,2019-08-06T06:45:10Z,1,"while training the data I encountered an error... ""You must feed a value for placeholder tensor 'input_1/X' with dtype float and shape [?,50,50,1]""... Can Anyone help?",True
@hafitalaqouri3322,2019-06-20T00:45:59Z,0,You're awesome from Libya,True
@michaelutah98,2019-06-12T17:26:33Z,0,"i have been following this video and i must say its been good so far. so im actually applying the knowledge from here on my personal project. i got an error and i dont know if you can help me figure it out thanks 'ValueError: cannot reshape array of size 74463900 into shape (50,50,1)'",True
@flycwbg,2019-05-23T04:08:38Z,0,i can not activate tensorboard. the path setting is not correct for log.... I guess it also causes the curve in the video,True
@nickcarmont4776,2019-05-05T08:33:21Z,0,"If anyone has problems with Tensorflow/python 3.7 versions, follow this: https://github.com/jeffheaton/t81_558_deep_learning",True
@md.sakirhossain2267,2019-05-04T15:26:24Z,0,"Thanks man, an amazing tutorial. i'm doing my project on MRI brain classification using cnn. datasets are in .mha file format. I'm using simpleITK library .But how can i generate images from .mha file?",True
@vatsaldholakiya4991,2019-03-18T07:29:53Z,1,"i keep getting ValueError: Cannot feed value of shape (64, 50, 50, 1) for Tensor 'input/X:0', which has shape '(?, 28, 28, 1)' can anyone explain?",True
@kafkatamurra,2019-03-02T16:05:53Z,1,everything was cool until i came to model.fit part. but now i have too many error that i could not fix.,True
@sohaib_recitor,2019-02-28T23:18:26Z,0,my model is not loaded ........can anyone help,True
@Ahmed.Shaikh,2018-12-17T08:15:13Z,0,"model.fit({'input': X}, {'targets': Y}, n_epoch=3, validation_set=({'input': test_x}, {'targets': test_y}),      snapshot_step=500, show_metric=True, run_id=MODEL_NAME)",True
@akramsystems,2018-12-14T04:07:11Z,0,"thank you x1,000,000,000 !!!",True
@anishadjmerabet5237,2018-12-03T17:30:32Z,5,"hello, I have a problem concerning TENSORBOARD : No dashboards are active for the current data set",True
@wakdol77,2018-10-31T04:43:24Z,0,"I got this type of error. How can I solve this problem ?       Run id: normalvsabnormal-0.001-2conv-basic.model Log directory: log/ INFO:tensorflow:Summary name Accuracy/ (raw) is illegal; using Accuracy/__raw_ instead. --------------------------------- Training samples: 85 Validation samples: 5 -- --------------------------------------------------------------------------- TypeError                                 Traceback (most recent call last) <ipython-input-10-fb036d84fe39> in <module>       1 model.fit({'input': X}, {'targets': Y}, n_epoch=1, validation_set=({'input': test_x}, {'targets': test_y}),  ----> 2     snapshot_step=5, show_metric=True, run_id=MODEL_NAME)  C:\ProgramData\Anaconda3\lib\site-packages\tflearn\models\dnn.py in fit(self, X_inputs, Y_targets, n_epoch, validation_set, show_metric, batch_size, shuffle, snapshot_epoch, snapshot_step, excl_trainops, validation_batch_size, run_id, callbacks)     214                          excl_trainops=excl_trainops,     215                          run_id=run_id, --> 216                          callbacks=callbacks)     217      218     def fit_batch(self, X_inputs, Y_targets):  C:\ProgramData\Anaconda3\lib\site-packages\tflearn\helpers\trainer.py in fit(self, feed_dicts, n_epoch, val_feed_dicts, show_metric, snapshot_step, snapshot_epoch, shuffle_all, dprep_dict, daug_dict, excl_trainops, run_id, callbacks)     337                                                        (bool(self.best_checkpoint_path) | snapshot_epoch),     338                                                        snapshot_step, --> 339                                                        show_metric)     340      341                             # Update training state  C:\ProgramData\Anaconda3\lib\site-packages\tflearn\helpers\trainer.py in _train(self, training_step, snapshot_epoch, snapshot_step, show_metric)     816         tflearn.is_training(True, session=self.session)     817         _, train_summ_str = self.session.run([self.train, self.summ_op], --> 818                                              feed_batch)     819      820         # Retrieve loss value from summary string  ~\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\client\session.py in run(self, fetches, feed_dict, options, run_metadata)     885     try:     886       result = self._run(None, fetches, feed_dict, options_ptr, --> 887                          run_metadata_ptr)     888       if run_metadata:     889         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)  ~\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\client\session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)    1077             feed_handles[subfeed_t] = subfeed_val    1078           else: -> 1079             np_val = np.asarray(subfeed_val, dtype=subfeed_dtype)    1080     1081           if (not is_tensor_handle_feed and  C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\numeric.py in asarray(a, dtype, order)     499      500     """""" --> 501     return array(a, dtype, copy=False, order=order)     502      503   TypeError: float() argument must be a string or a number, not 'NoneType'   ​",True
@souha5188,2018-09-11T08:32:26Z,0,"I want to use the same algorithm and change the classes for 8 classess , what should I do ???",True
@mahaomolise5359,2018-09-04T21:48:11Z,0,how do i solve this  NameError: name 'model' is not defined,True
@sujaya5703,2018-08-08T14:29:22Z,0,How to train frames in video using cnn ?,True
@alexhoffendahl8486,2018-07-23T20:01:59Z,1,"hi sir, I came across an issue at the running model.fit, and couldn't know exactly what the problem was. Could you help me please?  --------------------------------- Run id: dogsvscats-0.001-2conv-basic.model Log directory: log/ INFO:tensorflow:Summary name Accuracy_4/Adam_0 (raw) is illegal; using Accuracy_4/Adam_0__raw_ instead. INFO:tensorflow:Summary name Accuracy_5/Adam_1 (raw) is illegal; using Accuracy_5/Adam_1__raw_ instead. --------------------------------- Training samples: 147000 Validation samples: 3000 -- --------------------------------------------------------------------------- InvalidArgumentError                      Traceback (most recent call last) ~/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)    1321     try: -> 1322       return fn(*args)    1323     except errors.OpError as e:  ~/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)    1306       return self._call_tf_sessionrun( -> 1307           options, feed_dict, fetch_list, target_list, run_metadata)    1308   ~/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py in _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)    1408           self._session, options, feed_dict, fetch_list, target_list, -> 1409           run_metadata)    1410     else:  InvalidArgumentError: You must feed a value for placeholder tensor 'input_1/X' with dtype float and shape [?,50,50,1]   [[Node: input_1/X = Placeholder[dtype=DT_FLOAT, shape=[?,50,50,1], _device=""/job:localhost/replica:0/task:0/device:CPU:0""]()]]  During handling of the above exception, another exception occurred:",True
@AtulSharma-xw4qk,2018-07-19T11:41:58Z,0,I guess we missed normalising the data because of which accuracy is pretty low. (X=X/255.0),True
@hugokisebwe9862,2018-07-18T09:03:22Z,0,I have this error with model.fit() : ValueError: setting an array element with a sequence. Can someone helps please ??,True
@kalankasiyambalapitiya7615,2018-07-17T10:58:37Z,1,"I am using anaconda on python 3.6.5 verison but it gives me `keep_dims is deprecated,use keepdims instead`error. what will be the reason here?",True
@mockingbird3809,2018-07-08T17:19:55Z,6,TENSORBOARD ERROR No dashboards are active for the current data set. please help me,True
@shivamp5410,2018-07-02T19:21:52Z,2,Everything worked until the model.fit part. I keep getting the error in model.fit()  TypeError: float() argument must be a string or a number.,True
@vinayaktyagi8773,2018-06-28T10:40:48Z,0,"Sorry, But got an error in model.fit()  fun  "" TypeError: float() argument must be a string or a number, not 'NoneType' "" PLzzzzzzz HELP!!!!",True
@kishangovind8499,2018-06-13T13:36:08Z,0,is there a relation on the number of parameters and the number of samples ?,True
@HuntedGamerFilms,2018-06-06T00:03:46Z,0,I TYPE: tensorboard --logdir=foo:Desktop\CNN\log  I GET ERROR: Your CPU supports Instructions that this TensorFlow binary was not compiled to use: AVX2 TensorBoard 1.8.0 AND THIS ERROR: FutureWarning: Conversion of the second argument of issubdtype from 'float' to 'np.floating' is depricated,True
@robosergTV,2018-05-20T21:00:53Z,2,"why do you reshape already reshape images and why do you use .reshape(-1,IMG_SIZE,IMG_SIZE,1) instead of .reshape(IMG_SIZE,IMG_SIZE) ?",True
@charlitopiaojr.6945,2018-05-14T11:20:04Z,2,"I've created another test that is independent from the train_data and I've had an error which is:   ValueError: setting an array element with a sequence.  Can anybody help me with this?   this is a snippet of my code in training: train = train_data[:] validate = validate_data[:]  test_x = np.array([i[0] for i in validate]).reshape(-1, IMG_SIZE, IMG_SIZE, 1) test_y = [i[1] for i in validate]  model.fit({'input': X}, {'targets': Y}, n_epoch=7, validation_set=({'input': test_x}, {'targets': test_y}),           snapshot_step=500, show_metric=True, run_id=MODEL_NAME)  the error seems to be during training in model.fit    PLEASE HELP>!!!",True
@mohitruke682,2018-04-09T03:22:14Z,0,Can we initialialize tensorboard even if we are on CPU?,True
@user-gu1sv3ct4f,2018-03-23T09:13:37Z,0,What does it means:  train = train_data[:-500] test = train_data[-500:]  we do not use 500 images from training data ?,True
@ManishKumar-cc2kv,2018-03-17T19:48:42Z,2,"When running the model.fit cell I'm getting this error:  Cannot feed value of shape (64, 2) for Tensor 'targets/Y:0', which has shape '(?, 10)' can anyone help me",True
@archimedesspiral,2018-03-14T23:33:50Z,0,"Sendtex, appreciate all your videos. Regarding tensorboard, got stuck at the path. when you create model = tflearn.DNN(convnet, tensorboard_dir='log'), it won't save at the default location where you save your python files. For me, my location was more at #tensorboard --logdir=foo:C:\Users\*****\log\dogsvscats-1e-05-6conv-basic-video.model. Check your prompt for the messages. Search *dogsvscat*, hopefully windows will live you the path your log is stored.",True
@davidkombe3718,2018-03-14T18:48:08Z,0,"When running the model.fit cell I'm getting this error:  InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'input_1/X' with dtype float and shape [?,50,50,1]   [[Node: input_1/X = Placeholder[dtype=DT_FLOAT, shape=[?,50,50,1], _device=""/job:localhost/replica:0/task:0/device:CPU:0""]()]]  Can someone please help me out, what could this be?",True
@shekharbanerjee9738,2018-03-10T09:40:33Z,0,the tensorboard can't read the event files . How do i fix it??,True
@pratyushsrivastava2098,2018-02-27T11:43:48Z,2,I am not able to load the model again once I have done the training every time again starts training  I am coding on ubuntu,True
@dhanashreemane7873,2018-02-16T20:33:49Z,0,"Hi, I am new to this field. Trying out this code. But I am getting an error while installing tflearn.  ""TypeError: parse() got an unexpected keyword argument 'transport_encoding'"" Can anyone help me on this? Thanks, Dhanashree",True
@ssesefsefa,2018-01-24T12:20:14Z,0,"I am student from Turkey. I have a graduation project in tihs year. And i have a few days to finish that.My project is detecting street animals. So they are : Cats,Dogs and birds. I checked up your tutorial ""Classifying Cats and Dosg"" but i need triple version of this. So classifying multiple(3 enough for me) images. How can i do this using your method? Please help me.  Regards.",True
@jasonchong8330,2018-01-16T09:39:07Z,0,Hi I cant launch tensorboard on Windows. It says Module 'sys' has no attribute 'getdlopenflags'. Please help!!!,True
@vijaykumarkari,2017-12-17T12:34:12Z,0,"hai ..i was trying with ur code...but am getting like this-->summ = tf.scalar_summary(tag, value)  AttributeError: module 'tensorflow' has no attribute 'scalar_summary'   plz help me to resolve this error thnk you",True
@khadidjabenchaira6004,2017-12-16T21:02:07Z,0,Thank You very much for your great tutorials ...,True
@thehellraiserap7,2017-12-15T05:53:30Z,1,Hi @sentdex thanks again for this amazing video series.  When i run the command for tensorboard in terminal i get this error:  ValueError: A logdir must be specified when db is not specified.  Any suggestions?,True
@eplanti,2017-11-29T02:12:55Z,0,"i've been wondering, what would happen if you started adding empty rooms to the training data?",True
@ahmedsaid2613,2017-09-29T13:44:02Z,0,"When I start training , the loss , accuracy , val_loss and val_accuracy never change ??? why is that happening although I preprocess my data according to your steps , to check whether I am wrong or not , I tried Keras Data augmentation and it perfectly worked ..???",True
@TheGamosh,2017-09-15T16:41:12Z,2,tf.reset_default_graph() Seems to solve some of the issues brought here in the comment section,True
@Jake3D,2017-09-13T05:46:05Z,3,"For windows to access TensorBoard on windows tensorboard --logdir=foo:""Dir\log"" where Dir is the location where you save your code. (Edit) the doulbe = isnt nessary. Note the double quotes around the directory because where I save my files there are spaces. If you save in a dir like C:\Python_TUT_Files then you don't need the quotes. However if you save ""C:\Users\User\Documents\Python Files\Tutorial Files\..."" you do need the quotes because of the space and don't forget to add \log at the end. Once you have executed this in command prompt you can use the IP address listed or use http://localhost:6006 both should work. If it says ""No dashboards are active for the current data set."" then the directory you entered is wrong in some way. Try and recopy the DIR and put it in quotes.  If this still isn't working for you you could try double = before the foo. It seemed like it was necessary for me but I was able to get it working without it as well.  Hope this Helps",True
@Schmuck,2017-08-17T16:53:25Z,0,"Like everyone else is asking, why are we reshaping into a 4d array? Why not a 3d of (24000, 50, 50)? What is that 1 at the end for?",True
@Speechrezz,2017-08-16T05:58:53Z,0,Can you show how to implement learning rate decay?,True
@partisanpuff9861,2017-07-31T21:35:10Z,0,INSTALL GENTOO,True
@user-cc9yv2cc7t,2017-07-23T10:32:24Z,0,"getting this error while training the model https://stackoverflow.com/questions/43817501/invalidargumenterror-you-must-feed-a-value-for-placeholder-tensor-input-1-x You must feed a value for placeholder tensor 'input_1/X' with dtype float erroer in the fit line: X = np.array([i[0] for i in train]).reshape(-1, IMG_SIZE, IMG_SIZE, 1) Y = np.array([i[1] for i in train])  test_x = np.array([i[0] for i in test]).reshape(-1, IMG_SIZE, IMG_SIZE, 1) test_y = np.array([i[1] for i in test])  model.fit({'input': X}, {'targets': Y}, n_epoch=5, validation_set=({'input': test_x}, {'targets': test_y}), snapshot_step=500, show_metric=True, run_id=MODEL_NAME)   i tried to change the numpy array's dtype like this : X = np.array([i[0] for i in train],dtype = np.float64).reshape(-1,IMG_SIZE,IMG_SIZE,1) Y = [i[1] for i in train]  test_x = np.array([i[0] for i in test],dtype = np.float64).reshape(-1,IMG_SIZE,IMG_SIZE,1) test_y = [i[1] for i in test]  still appear the same bug sentdex,do you know why?",True
@kenyafoster3916,2017-07-16T03:25:43Z,0,"I am getting this error:     return array(a, dtype, copy=False, order=order) ValueError: setting an array element with a sequence.  I created my own image training and testing folder. The train folder consist of 195 images and the testing has 160 images. I have 7 different labels for the images. What am I doing wrong to get this error?",True
@AM-wz5tg,2017-07-15T07:32:00Z,1,"Dear Eng.Harrison,   These videos are really impressive thanks for it. I have Traceback on ""model.fit({'input': X}, {'targets': Y}, n_epoch=3, validation_set=({'input': test_x}, {'targets': test_y}),      snapshot_step=500, show_metric=True, run_id=MODEL_NAME)"", could you help to fix it?",True
@GeneralWolffang07,2017-06-30T04:56:43Z,0,"Please help : run script, my error :return array(a, dtype, copy=False, order=order) ValueError: setting an array element with a sequence.",True
@salilgautam3837,2017-06-18T22:20:50Z,0,",in evaluate_flow     res = [r / dataflow.n_samples for r in res] ZeroDivisionError: float division by zero   Getting this error at 24448 iter of 001 epoch while fitting the model, how to fix this Please Help !",True
@urvishnakum914,2017-06-01T05:15:15Z,5,"sir , what is the purpose   .reshape (-1 , Img_size , Img_size , 1)    can you explain little bit sir ? .",True
@ryanshrott9622,2017-04-24T20:26:33Z,2,"If you are using anaconda, open the terminal for the tensorflow environment using conda, then type: python -m tensorflow.tensorboard --logdir=foo:C:\DogsVsCats\log",True
@ryanshrott9622,2017-04-24T18:50:51Z,0,"Can someone explain the purpose of the reshape into a 4-d array as written in the input_data(): shape=[None, IMG_SIZE, IMG_SIZE, 1]",True
@qazaqstan3085,2017-03-25T18:55:59Z,0,cool,True
@UntitledLT,2017-03-25T17:00:07Z,0,"T.y. so much for the tutorials! I am building an analogous architecture, but I am using 100x100 size and want the input to use color RGB data. I've changed the pic size variables and the convnet = input_data(shape=[None, IMG_SIZE, IMG_SIZE, 3], name='input'), but are there any other changes in the architecture of the net that should be adjusted?",True
@chaopan7205,2017-03-24T22:08:22Z,2,You actually didn't save the new model name.,True
@truthinengineering,2017-03-17T18:04:59Z,0,"tried to recreate this in keras, followed the video exactly, but get an error ""cannot apply softmax to a tensor that is not 2d or 3d. Here ndim = 4. "" I thought the images were 3d (50x50x1)? Any idea how to fix this?",True
@aravindemails,2017-03-05T09:28:31Z,0,"how did u get the tensorboard working with the data from this code.   File ""<ipython-input-24-430a7515ff53>"", line 1     tensorboard --logdir=/home/aravind/log                          ^ SyntaxError: invalid syntax   i have a error like this can u help me to sort out",True
@sachinjain6436,2017-03-04T05:00:20Z,0,"Do you know if there's any way I can speed up my model.fit method? Mine takes a little more than a minute for each epoch, while yours finishes them in almost 30 sec. I have a fairly new computer that should be able to handle these processes, so do you have any suggestions?",True
@luisortega7028,2017-03-03T03:42:55Z,0,"I would like to know if you have or plan to upload this class onto pythonprogramming.net  I get an error when running the model.fit segment. I've gone over my typing and cannot find where I mistyped. I would like to do a soft text file compare.  Thanks,",True
@raywilliams2078,2017-03-02T22:19:34Z,0,"Hello sentdex. Thank u for this great tutorial, but I got an error when i try to import tflearn using spyder. Error Message: ImportError: dlopen(/Users/MacBook/Anaconda/anaconda/lib/python2.7/lib-dynload/_curses.so, 2): Library not loaded: @rpath/libncursesw.5.dylib   Referenced from: /Users/MacBook/Anaconda/anaconda/lib/python2.7/lib-dynload/_curses.so   Reason: image not found I have searched google and brew installed ncurse, but nothing changes. Thx for your support.",True
@nikhilpandey2364,2017-02-26T05:21:43Z,1,"Man this model.fit, is it suppose to work in python 2 same as shown in python 3 or something else? I am getting the following errors: InvalidArgumentError                      Traceback (most recent call last) <ipython-input-54-a29ec71e4656> in <module>()       2           snapshot_step=50,       3           show_metric=True, ----> 4           run_id=MODEL_NAME)  I think i have been stupid somewhere but don't know where.",True
@nikhilpandey2364,2017-02-26T05:09:43Z,8,"Hey man, you were right, it does throw super disgusting errors!",True
@anmol9096,2017-02-25T11:35:15Z,0,"Hello sir, I am running tensorflow on windows by the help of docker and oracle virtual box. The jupyter notebook running at port 8888 doesn't show me the directories where I have my training and testing data. If I try to upload the files in the notebook, it says that can't upload files greater than 25 Mb. In this tutorial series, when I try to use os.libdir(TRAIN_DIR), I get the following error : ""No such file or directory found"". Can you please help resolving this issue. Thanks in advance.",True
@owjhturem8205,2017-02-24T03:26:31Z,0,"sentdex, do you have plan to lecture cython and Numba??",True
@silakanveli,2017-02-23T20:06:24Z,0,what is that dev environment/ide?,True
@ulm287,2017-02-22T19:53:13Z,0,Great Video again !,True
