author,updated_at,like_count,text,public
@firstpagemarketing,2015-08-19T00:43:20Z,0,"I am not sure if the packages have updated  and some of the code has to be altered but as is. I got a ""main loop index 247 is out of bounds for axis 0 with size 247.  I also got an error message with the aroon by itself saying at the end. Traceback (most recent call last): File ""C:\Python\Aroon.py"", line 46, in aroon(20) File ""C:\Python\Aroon.py"", line 37, in aroon print highp[x] IndexError: index 106 is out of bounds for axis 0 with size 106.  It prints out but produces that error.  I changed line 37 from while x < len(date):  to  while x < len(date)-1:  the error message no longer comes up i then put that on the chart and the chart comes up.  I""m still getting the following at the end  Warning (from warnings module):   File ""C:\Python27\lib\site-packages\matplotlib\collections.py"", line 590     if self._edgecolors == str('face'): FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison    I haven't figured this out since there is not 590 lines.",True
