author,updated_at,like_count,text,public
@EhsanZia-Academi,2024-02-28T03:17:42Z,0,Thank you Sir for this great video. How can I use converter for python 3? in Python 3 it couldn't find strpdate2num,True
@JmanBC,2023-11-26T00:08:16Z,0,"This is the updated code for 3.11  import time as time import matplotlib.pyplot as plt import matplotlib.ticker as mticker import matplotlib.dates as mdates import numpy as np from matplotlib import style  style.use(""ggplot"")     def graphRawFX():     date,bid,ask = np.genfromtxt('GBPUSD1d.txt', unpack=True,                               delimiter=',',                               converters={0: mdates.datestr2num})                             #converters={0:mdates.strpdate2num('%Y%m%d%H%M%S')})      fig=plt.figure(figsize=(10,7))      ax1 = plt.subplot2grid((40,40), (0,0), rowspan=40, colspan=40)     ax1.plot(date,bid)     ax1.plot(date,ask)      ax1.xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%D %H:%M:%S'))      for label in ax1.xaxis.get_ticklabels():             label.set_rotation(45)     plt.subplots_adjust(bottom=.23)     plt.gca().get_yaxis().get_major_formatter().set_useOffset(False)     plt.grid(True)     plt.show()",True
@yaserrostamijoghal7326,2022-03-11T11:42:08Z,0,Excellent,True
@veniciussoaresdasilva6614,2021-02-25T10:53:23Z,3,"Show the graph properly use the code below     date,bid,ask = np.loadtxt('GBPUSD1d.txt', unpack=True,                               delimiter=',',                               converters={0: lambda x: mdates.datestr2num(x.decode('utf8'))})",True
@GoredGored,2020-10-27T19:24:07Z,1,"A question to all Python Gurus...sentdex thank you for the videos. A quick question why you used loadtext instead of read_csv...is there any reason? pd.read_csv('GBPUSD1d.txt', header=None).values And then I can plot as shown in your tutorial. Am I missing something why used numpy instead of pandas?  Thanks",True
@mohammadmustaqaliqadri2396,2020-05-18T07:23:12Z,1,"Thanks to Super Z, The working code in python 3 is below : import matplotlib import pandas as pd import matplotlib.pyplot as plt import matplotlib.ticker as mticker import matplotlib.dates as mdates import numpy as np import datetime as dt  def graphRawFX():     GBP = pd.read_csv('GBPUSD1d.txt', header=None, delimiter=',', names=['a', 'b', 'c'], parse_dates=['a'])      GBP.set_index(GBP['a'], inplace=True)     fig = plt.figure(figsize=(10, 7))     ax1 = plt.subplot2grid((40, 40), (0, 0), rowspan=40, colspan=40)      ax1.plot(GBP['a'], GBP['b'])     ax1.plot(GBP['a'], GBP['c'])     ax1.xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d'))     plt.grid(True)     plt.show()  graphRawFX()",True
@Bryant220225,2020-05-06T06:16:56Z,0,Thank you for this. Is all of the data provided still available and relevant. In other words will the process still work?,True
@mwyee,2020-03-23T14:48:45Z,0,"When I run the above I kept getting the following error:      `File ""<ipython-input-31-75d4876642f2>"", line 4       converters={0:mdates.strpdate2num('%Y%m%d%H%M%S')})              ^       SyntaxError: invalid syntax",True
@ryandicks6813,2020-03-04T10:36:08Z,0,"same problem, this stuff is old, Please remove this.",True
@thebanana835,2019-10-12T08:03:58Z,0,What IDE are you using.  I am using Spyder and tried IDLE but they are not working....,True
@rameezfredericks5967,2019-10-05T14:31:19Z,1,Thanks for this - i've been trading for a long time but this will allow me to get better and get to the next level,True
@AndrewBecker1,2019-07-20T21:41:03Z,2,If you are doing this with Python 3 then change 'strpdate2num' to 'bytespdate2num' and put 'graphRawFX()' at the end of your python script in line with the def to call the method.,True
@MarvoloRiddle,2019-07-16T14:05:49Z,0,I get an error around the part where you're putting values into fig.,True
@ericabao1279,2019-07-09T15:52:31Z,0,https://github.com/matplotlib/matplotlib/issues/4126/   this issue can fix the problem of fig.,True
@rowen40,2019-01-01T13:49:32Z,1,"Hi, I am a newbee and try to make this script work on my Mac. The graph don't show up. I got this identification error:   File ""/Users/wendy/.spyder/untitledtest.py"", line 16     date,bid,ask = np.loadtxt('GBPUSD1d.txt, unpack=True,)        ^ I don't know how to fix this. Has it got something to do with that the scrypt is not finding the downloaded GBPUSDfiles? Can you please help? Thanks",True
@mt.erebus3370,2018-12-11T18:40:55Z,2,"Hey sentdex, hope it's okay. I updated the code to work on Jupyter Notebook for those who were not able to view a graph. I had a little trouble with the timestamp, but after some googling i figured it. Code works fine for me. Hope this helps anyone else.   import matplotlib import pandas as pd import matplotlib.pyplot as plt import matplotlib.ticker as mticker import matplotlib.dates as mdates import numpy as np import datetime as dt  fig = plt.figure() ax1 = plt.subplot()  def graph():     GBP= pd.read_csv('GBPUSD1d.txt',header=None, delimiter=',',names=['a','b','c'], parse_dates=['a'])          GBP.set_index(GBP['a'],inplace=True)          ax1.plot(GBP['a'],GBP['b'])     ax1.plot(GBP['a'],GBP['c'])     ax1.xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d'))  graph()",True
@Punderland,2018-08-28T19:30:23Z,0,"import matplotlib import matplotlib.pyplot as plt import matplotlib.ticker as mticker import matplotlib.dates as mdates import numpy as np   def graphRawFx():     date,bid,ask=np.loadtxt('GBPUSD1d.txt',unpack=True, delimiter=',',converters={0:mdates.strpdate2num('%Y/%m/%d/%H/%M/%S')})     fig=plt.figure(figsize=(10,7))     ax1=plt.subplot2grid((40,40),(0,0),rowspan=40,colspan=40)      ax1.plot(date,bid)     ax1.plot(date,ask)      ax1.xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d %H:%M:%S'))      plt.grid(True)     plt.show() ===============================Console Error Message============================= (venv) C:\Users\Punderland\PycharmProjects\MLearning\venv>python Python 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)] on win32 Type ""help"", ""copyright"", ""credits"" or ""license"" for more information. >>> import AlgoTrade2 as ATT >>> ATT.graphRawFx() Traceback (most recent call last):   File ""<stdin>"", line 1, in <module>   File ""C:\Users\Punderland\PycharmProjects\MLearning\venv\AlgoTrade2.py"", line 9, in graphRawFx     date,bid,ask=np.loadtxt('GBPUSD1d.txt',unpack=True, delimiter=',',converters={0:mdates.strpdate2num('%Y%m%d%H%M%S')})   File ""C:\Users\Punderland\PycharmProjects\MLearning\venv\lib\site-packages\numpy\lib\npyio.py"", line 1092, in loadtxt     for x in read_data(_loadtxt_chunksize):   File ""C:\Users\Punderland\PycharmProjects\MLearning\venv\lib\site-packages\numpy\lib\npyio.py"", line 1019, in read_data     items = [conv(val) for (conv, val) in zip(converters, vals)]   File ""C:\Users\Punderland\PycharmProjects\MLearning\venv\lib\site-packages\numpy\lib\npyio.py"", line 1019, in <listcomp>     items = [conv(val) for (conv, val) in zip(converters, vals)]   File ""C:\Users\Punderland\PycharmProjects\MLearning\venv\lib\site-packages\numpy\lib\npyio.py"", line 1078, in tobytes_first     return conv(x.encode(""latin1""))   File ""C:\Users\Punderland\PycharmProjects\MLearning\venv\lib\site-packages\matplotlib\dates.py"", line 360, in __call__     return date2num(datetime.datetime(*time.strptime(s, self.fmt)[:6]))   File ""C:\Users\Punderland\Miniconda3\lib\_strptime.py"", line 559, in _strptime_time     tt = _strptime(data_string, format)[0]   File ""C:\Users\Punderland\Miniconda3\lib\_strptime.py"", line 329, in _strptime     raise TypeError(msg.format(index, type(arg))) TypeError: strptime() argument 0 must be str, not <class 'bytes'> ========================================================================================= Please help!!! @____________________@",True
@mdantzis,2018-07-27T02:47:42Z,0,"Thanks for the class i have an issue with   '""converters={0:mdates.strpdate2num('%Y%m%d%H%M%S')}"" i get a: TypeError: strptime() argument 0 must be str, not <class 'bytes'> the entire stack of the error is:  import matplotlib import matplotlib.pyplot as plt import matplotlib.ticker as mticker import matplotlib.dates as mdates import numpy as np  def graphRawFX():     date,bid,ask = np.loadtxt('GBPUSD1d.txt',                               unpack=True, delimiter=',',                               converters={0:mdates.strpdate2num('%Y%m%d%H%M%S')})     fig = plt.figure(figsize=(10,7))     ax1 = plt.subplot2grid((40,40),(0,0),rowspan=40,colspan=40)      ax1.plot(date,bid)     ax1.plot(date,ask)      ax1.xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d  %H:%M:%S'))      plt.grid(True)     plt.show()  graphRawFX() --------------------------------------------------------------------------- TypeError                                 Traceback (most recent call last) <ipython-input-2-accd7af34f05> in <module>() ----> 1 graphRawFX()  <ipython-input-1-089315f1ef95> in graphRawFX()       8     date,bid,ask = np.loadtxt('GBPUSD1d.txt',       9                               unpack=True, delimiter=',', ---> 10                               converters={0:mdates.strpdate2num('%Y%m%d%H%M%S')})      11     fig = plt.figure(figsize=(10,7))      12     ax1 = plt.subplot2grid((40,40),(0,0),rowspan=40,colspan=40)  C:\ProgramData\Anaconda3\lib\site-packages\numpy\lib\npyio.py in loadtxt(fname, dtype, comments, delimiter, converters, skiprows, usecols, unpack, ndmin, encoding)    1090         # converting the data    1091         X = None -> 1092         for x in read_data(_loadtxt_chunksize):    1093             if X is None:    1094                 X = np.array(x, dtype)  C:\ProgramData\Anaconda3\lib\site-packages\numpy\lib\npyio.py in read_data(chunk_size)    1017     1018             # Convert each value according to its column and store -> 1019             items = [conv(val) for (conv, val) in zip(converters, vals)]    1020     1021             # Then pack it according to the dtype's nesting  C:\ProgramData\Anaconda3\lib\site-packages\numpy\lib\npyio.py in <listcomp>(.0)    1017     1018             # Convert each value according to its column and store -> 1019             items = [conv(val) for (conv, val) in zip(converters, vals)]    1020     1021             # Then pack it according to the dtype's nesting  C:\ProgramData\Anaconda3\lib\site-packages\numpy\lib\npyio.py in tobytes_first(x, conv)    1076                     if type(x) is bytes:    1077                         return conv(x) -> 1078                     return conv(x.encode(""latin1""))    1079                 import functools    1080                 converters[i] = functools.partial(tobytes_first, conv=conv)  C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\dates.py in __call__(self, s)     358            return value: a date2num float     359         """""" --> 360         return date2num(datetime.datetime(*time.strptime(s, self.fmt)[:6]))     361      362   C:\ProgramData\Anaconda3\lib\_strptime.py in _strptime_time(data_string, format)     557     """"""Return a time struct based on the input string and the     558     format string."""""" --> 559     tt = _strptime(data_string, format)[0]     560     return time.struct_time(tt[:time._STRUCT_TM_ITEMS])     561   C:\ProgramData\Anaconda3\lib\_strptime.py in _strptime(data_string, format)     327         if not isinstance(arg, str):     328             msg = ""strptime() argument {} must be str, not {}"" --> 329             raise TypeError(msg.format(index, type(arg)))     330      331     global _TimeRE_cache, _regex_cache  TypeError: strptime() argument 0 must be str, not <class 'bytes'>  any ideas?  thanks",True
@musasibuyi4765,2018-05-21T07:10:52Z,0,"Hi Harrison, in this method, i see the loadtxt function didnt have a closing bracket. i have written the same way as you have but i keep on getting an invalid syntax error. if i close the bracket, i get errors saying that the ""fig"" variable as well the ""plot"" functions dont exist. how do i solve this?",True
@RimGeurts,2018-03-17T22:20:08Z,0,magic! Thanks a ton for sharing this.,True
@tutorbase4982,2018-03-13T13:54:45Z,5,"Hey, i tried your method with python 3.6. no errors but graph does not appear. Any idea why?",True
@cocujo,2018-02-13T13:25:13Z,0,"Hi   I have the following error when I run the program:  Traceback (most recent call last):   File ""<stdin>"", line 1, in <module>   File ""AlgoTrading.py"", line 12, in graphRawFX     date,bid,ask = np.loadtxt('GBPUSD1d.txt', unpack=True,   File ""C:\Python27\lib\site-packages\numpy\lib\npyio.py"", line 1092, in loadtxt      for x in read_data(_loadtxt_chunksize):   File ""C:\Python27\lib\site-packages\numpy\lib\npyio.py"", line 1019, in read_da ta     items = [conv(val) for (conv, val) in zip(converters, vals)]   File ""C:\Python27\lib\site-packages\numpy\lib\npyio.py"", line 1078, in tobytes _first     return conv(x.encode(""latin1""))   File ""C:\Python27\lib\site-packages\matplotlib\dates.py"", line 312, in __call_ _     return date2num(datetime.datetime(*time.strptime(s, self.fmt)[:6]))   File ""C:\Python27\Lib\_strptime.py"", line 467, in _strptime_time     return _strptime(data_string, format)[0]   File ""C:\Python27\Lib\_strptime.py"", line 328, in _strptime     data_string[found.end():]) ValueError: unconverted data remains: 0000",True
@SanjeewaSilva,2018-01-23T12:20:14Z,0,can i use this for cryptocurrency data,True
@user-rm6jp4rt3n,2018-01-10T00:34:59Z,0,"import matplotlib import matplotlib.pyplot as plt import matplotlib.ticker as mticker import matplotlib.dates as mdates import numpy as np      def bytespdate2num(fmt, encoding='utf-8'):     strconverter = mdates.strpdate2num(fmt)     def bytesconverter(b):         s = b.decode(encoding)         return strconverter(s)     return bytesconverter       def graphRawFX():     date,bid,ask = np.loadtxt('GBPUSD1d.txt', unpack=True,                               delimiter=',',                               converters={0:bytespdate2num('%Y%m%d%H%M%S')})      fig=plt.figure(figsize=(10,7))      ax1 = plt.subplot2grid((40,40), (0,0), rowspan=40, colspan=40)     ax1.plot(date,bid)     ax1.plot(date,ask)      ax1.xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d %H:%M:%S'))      for label in ax1.xaxis.get_ticklabels():             label.set_rotation(45)     plt.subplots_adjust(bottom=.23)     plt.gca().get_yaxis().get_major_formatter().set_useOffset(False)     plt.grid(True)     plt.show() graphRawFX()",True
@debayansen3705,2017-12-21T06:51:49Z,0,"Traceback (most recent call last):   File ""<pyshell#1>"", line 1, in <module>     graphRawFX()   File ""C:/Users/Admin/AppData/Local/Programs/Python/Python35-32/algo.py"", line 10, in graphRawFX     converters={0:mdates.strpdate2num('%Y%m%d%H%M%S')})   File ""C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\numpy\lib\npyio.py"", line 1024, in loadtxt     items = [conv(val) for (conv, val) in zip(converters, vals)]   File ""C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\numpy\lib\npyio.py"", line 1024, in <listcomp>     items = [conv(val) for (conv, val) in zip(converters, vals)]   File ""C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\site-packages\matplotlib\dates.py"", line 289, in __call__     return date2num(datetime.datetime(*time.strptime(s, self.fmt)[:6]))   File ""C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\_strptime.py"", line 504, in _strptime_time     tt = _strptime(data_string, format)[0]   File ""C:\Users\Admin\AppData\Local\Programs\Python\Python35-32\lib\_strptime.py"", line 310, in _strptime     raise TypeError(msg.format(index, type(arg))) TypeError: strptime() argument 0 must be str, not <class 'bytes'>",True
@fajarreza1,2017-11-26T20:18:03Z,0,"Code run perfectly for python 2.7.14, no need to change. Other than x label looked overlapped, everything else are fine. Do not discourage others by posting lengthy, unnecessary corrections.",True
@cyl5207,2017-09-15T11:42:09Z,0,"if you get some Typeerror in this lesson, here is the fix. Please add this function below: def bytedate2num(fmt): def converter(b): return mdates.strpdate2num(fmt)(b.decode('ascii')) return converter  date_converter = bytedate2num('%Y%m%d%H%M%S')  and replace date_converter with mdates.strpdate2num('%Y%m%d%H%M%S') in def graphRawFX()",True
@antoniomarcos23,2017-06-13T04:54:21Z,0,"Spectacular lesson ... for me, I'm a beginner. Congratulations Sentdex!",True
@shrutiandkushal,2017-06-10T07:52:44Z,0,"hi there ,   i have runned the code in python 3.4 and i have done everything as per instructions, still it is showing error   this is the error:   Traceback (most recent call last):   File ""<pyshell#0>"", line 1, in <module>     graphRawFx()   File ""C:\Users\KushalDoDo\Desktop\1\first.py"", line 10, in graphRawFx     converters = {0:mdates.strpdate2num('%Y%m%d%H%M%S')})   File ""C:\Python34\lib\site-packages\numpy\lib\npyio.py"", line 848, in loadtxt     items = [conv(val) for (conv, val) in zip(converters, vals)]   File ""C:\Python34\lib\site-packages\numpy\lib\npyio.py"", line 848, in <listcomp>     items = [conv(val) for (conv, val) in zip(converters, vals)]   File ""C:\Python34\lib\site-packages\matplotlib\dates.py"", line 246, in __call__     return date2num(datetime.datetime(*time.strptime(s, self.fmt)[:6]))   File ""C:\Python34\lib\_strptime.py"", line 494, in _strptime_time     tt = _strptime(data_string, format)[0]   File ""C:\Python34\lib\_strptime.py"", line 306, in _strptime     raise TypeError(msg.format(index, type(arg))) TypeError: strptime() argument 0 must be str, not <class 'bytes'>    i am not able to debug it  please help",True
@michaelsylvia7562,2017-05-28T21:37:20Z,4,"After much research and trial and error, here is working code ran on Python 2.7.13:  import time import datetime import matplotlib import matplotlib.pyplot as plt import matplotlib.ticker as mticker import matplotlib.dates as mdates from datetime import datetime import numpy as np  def graphRawFX():     # Converter function     datefunc = lambda x: mdates.date2num(datetime.strptime(x, '%Y%m%d%H%M%S'))     # Read data from 'file.dat'     date, bid, ask = np.genfromtxt('GBPUSD1d.txt',    # Data to be read                                   delimiter=',',                                     converters={0: datefunc},                                    dtype=float,   # All values are floats                                   unpack=True)     fig = plt.figure(figsize=(10,7))     ax1= plt.subplot2grid((40,40), (0,0), rowspan=40, colspan=40)     ax1.plot(date,bid)     ax1.plot(date,ask)      ax1.xaxis.set_major_formatter(mdates.DateFormatter('%y-%m-%d %H:%M:%S'))     for label in ax1.get_xticklabels():         label.set_rotation(45)       plt.gca().get_yaxis().get_major_formatter().set_useOffset(False)      plt.grid(True)     plt.show() graphRawFX()",True
@michaelsylvia7562,2017-05-26T21:28:10Z,6,"Hi Harrison,  I am running into some issues with plt.show(). I have written this script nearly verbatim as detailed in this video and I have turned to StackOverflow to update any syntax, yet I have not been able to actually view this graph. Nothing comes up when I run the script, the shell just spits out '>>'.  I have changed backends, unistalled, upgraded and reinstalled matplotlib. I've also tried this script on the exact version of Python seen in this video as well as 3.6.1 and a few others on OS X and Windows 10 via Parallels - still running into the same issue. Any thoughts on a solution? Thanks so much.",True
@abhinavgupta9967,2017-04-17T01:40:50Z,0,"i am getting an error while running the program i am using phython 2.7.13. little help  needed  Traceback (most recent call last):   File ""<pyshell#2>"", line 1, in <module>     graphRawFX() NameError: name 'graphRawFX' is not defined",True
@scottcornish9005,2017-04-03T07:43:27Z,0,I get the same error message as a couple of others NameError:  name 'date' is not defined,True
@willlemerond1016,2017-03-21T03:43:12Z,0,"i tried this code exactly as is and the other examples, always same error: date is not defined.",True
@willlemerond1016,2017-03-21T03:27:50Z,0,"Hello there, want to let you know how much I greatly appreciate the tutorial. However, it keeps saying ""name 'date' is not defined"". Isnt this defined under the function name?",True
@uThank,2017-03-06T02:05:24Z,0,"I draw 2000 lines ,463 point per line , then it become really slow to zoom in and zoom, Do i need to change the plot tool, or change my computer?",True
@justinfung5702,2016-10-22T02:16:28Z,0,Hello. Thanks for your nice video!! I have a problem with the graph plotted. I don't know why there is a shift on the x-axis to the right. That means the starting date in my graph is not '2013-05-01' but '2013-04-30' instead. How can I fix it?? Thank you,True
@sujithsstorock1,2016-10-13T09:51:06Z,16,"working codes for python 3.5  import time import datetime import matplotlib import matplotlib.pyplot as plt import matplotlib.ticker as mticker import matplotlib.dates as mdates import numpy as np def graphRawFx():     date,bid,ask = np.loadtxt('GBPUSD1d.txt',                                  unpack=True,                                  delimiter=',',                                  converters={0:mdates.bytespdate2num('%Y%m%d%H%M%S')})     # numpy passes a byte string to the converter instead of a string. In python 2, since bytes and str are equivalent it does not matter. For python 3, however, this results in an error as strpdate2num passes it to the standard library's strptime which only expects a string.     fig = plt.figure(figsize=(10,7))     ax1= plt.subplot2grid((40,40), (0,0), rowspan=40, colspan=40)     ax1.plot(date,bid)     ax1.plot(date,ask)          ax1.xaxis.set_major_formatter(mdates.DataFormatter('%y-%m-%d %H:%M:%S'))          plt.grid(True)     plt.show()  graphRawFx()",True
@Mr.Plutonium,2016-07-26T04:45:27Z,0,I am using El Capitan:   Could not open font file /Library/Fonts/NISC18030.ttf Could not open font file /System/Library/Fonts/Apple Color Emoji.ttf  Graph isn't opening...,True
@b.celestine384,2016-07-05T17:27:31Z,0,"Hello, I'm having a problem running the script on python and I tried everything to resolve it and still no progress. it keeps giving me the same error- Traceback (most recent call last):   File ""<pyshell#0>"", line 1, in <module>     graphRawFX()   File ""C:/Users/LoveCountyPawn/Desktop/Pip machine/Python algo trading/Data.py"", line 15, in graphRawFX     converters={0:mdates.strpdate2num('%Y%m%d%H%M%S')})   File ""C:\Python34\lib\site-packages\numpy\lib\npyio.py"", line 805, in loadtxt     fh = iter(open(fname)) FileNotFoundError: [Errno 2] No such file or directory: 'C:/LoveCountyPawn/Desktop/Pip machine/Python algo trading/GBPUSD1D'",True
@Marcos10PT,2016-06-15T11:52:35Z,0,The function doesn't run for me unless I call it. Is it supposed to run by itself? wtf?,True
@superz7940,2016-05-21T13:10:01Z,0,"hey, i am from china. i just took a afternoon to install py2.7 with  all  file. i find a url  include all file in google cloud drive :https://drive.google.com/folderview?id=0B83bAuUUiuy2TnVTV0JhdzBqcDg&usp=sharing",True
@s0me0ne11100,2016-02-20T14:28:50Z,0,"I got this error ""NameError: name 'bid' is not defined"". What is wrong?  import matplotlib import matplotlib.pyplot as plt import matplotlib.ticker as mticker import matplotlib.dates as mdates import numpy as np import datetime date = datetime.date.today()  def graphRawFX():      date,bid,ask = np.loadtxt('GBPUSD1d.txt', unpack=True,                                delimiter=',',                               converters={0:mdates.strpdate2num('%Y%m%d%H%M%S')})  fig = plt.figure(figsize=(10,7)) ax1 = plt.subplot2grid((40,40), (0,0), rowspan=40, colspan=40)  ax1.plot(date,bid) ax1.plot(date,ask)  ax1.xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d %H:%M:%S'))  plt.grid(True) plt.show()",True
@binaypoudel,2016-02-19T12:54:11Z,0,"I am not getting the graph part always .The problem is that, sometimes the graph is popped which  is cool but sometimes the graph doesnt appear and pops the dailogue box as Runtime Error!!( MIcrosoft visual C++ Runtime library)",True
@programmerqdev,2015-11-30T14:26:18Z,0,I tried to run and I got a Name Error. Only difference between your environment and mine is that I'm using Python 2.7.9. Would that be in any effect to what we're doing here?,True
@nickfelstead7559,2015-11-16T11:29:27Z,2,"i dont know what im doing wrong i keep on getting the following message (please not i am using python 3.5 n later versioins of matplotlib and numpy): Traceback (most recent call last):   File ""<pyshell#8>"", line 1, in <module>     graphRawFX()   File ""C:/Python Forex/python forex.py"", line 9, in graphRawFX     converters={0:mdates.strpdate2num('%Y%m%d%H%M%S')})   File ""C:\Users\Nick\AppData\Local\Programs\Python\Python35\lib\site-packages\numpy\lib\npyio.py"", line 813, in loadtxt     items = [conv(val) for (conv, val) in zip(converters, vals)]   File ""C:\Users\Nick\AppData\Local\Programs\Python\Python35\lib\site-packages\numpy\lib\npyio.py"", line 813, in <listcomp>     items = [conv(val) for (conv, val) in zip(converters, vals)]   File ""C:\Users\Nick\AppData\Local\Programs\Python\Python35\lib\site-packages\matplotlib\dates.py"", line 305, in __call__     return date2num(datetime.datetime(*time.strptime(s, self.fmt)[:6]))   File ""C:\Users\Nick\AppData\Local\Programs\Python\Python35\lib\_strptime.py"", line 494, in _strptime_time     tt = _strptime(data_string, format)[0]   File ""C:\Users\Nick\AppData\Local\Programs\Python\Python35\lib\_strptime.py"", line 306, in _strptime     raise TypeError(msg.format(index, type(arg))) TypeError: strptime() argument 0 must be str, not <class 'bytes'>  anyone help?",True
@0378jvp,2015-11-01T14:50:55Z,0,"Last login: Sun Nov  1 20:58:23 on ttys000 Jonel-Pericons-MacBook-Pro:~ jonelpericon$ cd desktop/Python_Lesson -bash: cd: desktop/Python_Lesson: No such file or directory Jonel-Pericons-MacBook-Pro:~ jonelpericon$ cd Desktop/Python_Lesson -bash: cd: Desktop/Python_Lesson: No such file or directory Jonel-Pericons-MacBook-Pro:~ jonelpericon$ cd Desktop\Python_Lesson -bash: cd: DesktopPython_Lesson: No such file or directory Jonel-Pericons-MacBook-Pro:~ jonelpericon$ cd Desktop Jonel-Pericons-MacBook-Pro:Desktop jonelpericon$ cd Python_Lessons Jonel-Pericons-MacBook-Pro:Python_Lessons jonelpericon$ python FirstLesson.py Traceback (most recent call last):   File ""FirstLesson.py"", line 1, in <module>     import matplotlib   File ""/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/__init__.py"", line 1131, in <module>     rcParams = rc_params()   File ""/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/__init__.py"", line 975, in rc_params     return rc_params_from_file(fname, fail_on_error)   File ""/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/__init__.py"", line 1100, in rc_params_from_file     config_from_file = _rc_params_in_file(fname, fail_on_error)   File ""/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/__init__.py"", line 1018, in _rc_params_in_file     with _open_file_or_url(fname) as fd:   File ""/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py"", line 17, in __enter__     return self.gen.next()   File ""/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/matplotlib/__init__.py"", line 1000, in _open_file_or_url     encoding = locale.getdefaultlocale()[1]   File ""/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py"", line 511, in getdefaultlocale     return _parse_localename(localename)   File ""/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py"", line 443, in _parse_localename     raise ValueError, 'unknown locale: %s' % localename ValueError: unknown locale: UTF-8 Jonel-Pericons-MacBook-Pro:Python_Lessons jonelpericon$",True
@ABKUoU,2015-10-19T08:30:55Z,0,"hey，can you tell me what idle you  use，or say ，what the python editor use in this  tutorial ^_^  I was searching a ligthweight idle or editor for python program,Thanks",True
@THISSHOWNEEDSMORETITS,2015-08-29T01:42:08Z,0,Why are you not including spread in graph analysis? is there a video you recommend that I check out to better explain spread?,True
@andreamarkos,2015-08-17T19:47:49Z,0,"hI sENTDEX, i MADE IT TO CLASS 2 BUT I AM GUESSING: IS PYTHON GOOD TO INTERFACE WITH TRADESTATION? THAT'S THE NEXT PLATFORM I AM GOING TO LEARN TO USE. THANKS FOR YOUR TIME AND FOR SHARING",True
@markrankin4078,2015-07-23T22:21:02Z,3,"Here's a workaround for anyone using Python 3.4 and has strpdate2num problems  import matplotlib import matplotlib.pyplot as plt import matplotlib.ticker as mticker import matplotlib.dates as mdates from matplotlib.dates import strpdate2num import numpy as np  def bytespdate2num(fmt, encoding='utf-8'):     strconverter = strpdate2num(fmt)     def bytesconverter(b):         s = b.decode(encoding)         return strconverter(s)     return bytesconverter  def graphRawFX():     date,bid,ask = np.loadtxt('GBPUSD1d.txt', unpack=True,                               delimiter=',',                               converters={0:bytespdate2num('%Y%m%d%H%M%S')})     fig = plt.figure(figsize =(10,7))     ax1 = plt.subplot2grid((40,40),(0,0), rowspan=40, colspan=40)      ax1.plot(date,bid)     ax1.plot(date,ask)      ax1.xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d %H: %M: %S'))      plt.grid(True)     plt.show()  graphRawFX()",True
@andreymamoshkin3546,2015-02-26T07:41:04Z,1,"Hi again)  Can you say where do I need to save this python script? I mean do I need to save it in a specified directore, as I run graphRawFX in python shell and it says that this name is not defined  Thank you)",True
@andreymamoshkin3546,2015-02-20T11:42:46Z,0,"Hi, thank you for your videos, but a have a stupid problem, please help me when I print fig = plt.figure(figsize(10,7)) after that python mark fig in the red colour and says as syntax error I just want to understand what's wrong with me, but why 'fig' is a syntax error? Thank you",True
@seanc.miller1349,2015-01-15T15:43:58Z,0,"Traceback (most recent call last):   File ""<pyshell#1>"", line 1, in <module>     graphRawFX()   File ""C:/Python27/Graph.py"", line 10, in graphRawFX     converters={0:mdates.strpdate2num('%Y%m%d%H%M%S')})   File ""C:\Python27\lib\site-packages\numpy\lib\npyio.py"", line 737, in loadtxt     fh = iter(open(fname, 'U')) IOError: [Errno 2] No such file or directory: 'GBPUSd1.txt'  Where can I locate this directory to store the txt file?",True
@ayushmehta5844,2015-01-01T20:09:42Z,0,"Traceback (most recent call last):   File ""<stdin>"", line 1, in <module>   File ""C:\Users\user\AppData\Local\Enthought\Canopy\User\lib\site-packages\matp lotlib\pyplot.py"", line 27, in <module>     import matplotlib.colorbar   File ""C:\Users\user\AppData\Local\Enthought\Canopy\User\lib\site-packages\matp lotlib\colorbar.py"", line 34, in <module>     import matplotlib.collections as collections   File ""C:\Users\user\AppData\Local\Enthought\Canopy\User\lib\site-packages\matp lotlib\collections.py"", line 27, in <module>     import matplotlib.backend_bases as backend_bases   File ""C:\Users\user\AppData\Local\Enthought\Canopy\User\lib\site-packages\matp lotlib\backend_bases.py"", line 56, in <module>     import matplotlib.textpath as textpath   File ""C:\Users\user\AppData\Local\Enthought\Canopy\User\lib\site-packages\matp lotlib\textpath.py"", line 19, in <module>     import matplotlib.font_manager as font_manager   File ""C:\Users\user\AppData\Local\Enthought\Canopy\User\lib\site-packages\matp lotlib\font_manager.py"", line 1412, in <module>     _rebuild()   File ""C:\Users\user\AppData\Local\Enthought\Canopy\User\lib\site-packages\matp lotlib\font_manager.py"", line 1397, in _rebuild     fontManager = FontManager()   File ""C:\Users\user\AppData\Local\Enthought\Canopy\User\lib\site-packages\matp lotlib\font_manager.py"", line 1052, in __init__     self.ttflist = createFontList(self.ttffiles)   File ""C:\Users\user\AppData\Local\Enthought\Canopy\User\lib\site-packages\matp lotlib\font_manager.py"", line 579, in createFontList     font = ft2font.FT2Font(fpath) TypeError: cannot return std::string from Unicode object  This error came just after running the second line i.e import matplotlib.pyplot as plt",True
@ayushmehta5844,2015-01-01T19:49:31Z,0,"%run ""G:/Sentdex/Machine Learning for Forex and Stock analysis and algorithmic trading/1st test program.py"" --------------------------------------------------------------------------- TypeError                                 Traceback (most recent call last) C:\Users\user\AppData\Local\Enthought\Canopy\App\appdata\canopy-1.4.1.1975.win-x86_64\lib\site-packages\IPython\utils\py3compat.pyc in execfile(fname, glob, loc)     195             else:     196                 filename = fname --> 197             exec compile(scripttext, filename, 'exec') in glob, loc     198     else:     199         def execfile(fname, *where):  G:\Sentdex\Machine Learning for Forex and Stock analysis and algorithmic trading\1st test program.py in <module>()       3 import numpy as np       4 import matplotlib.ticker as mticker ----> 5 import matplotlib.pyplot as plt       6 import matplotlib.dates as mdates       7   C:\Users\user\AppData\Local\Enthought\Canopy\User\lib\site-packages\matplotlib\pyplot.py in <module>()      25       26 import matplotlib ---> 27 import matplotlib.colorbar      28 from matplotlib import style      29 from matplotlib import _pylab_helpers, interactive  C:\Users\user\AppData\Local\Enthought\Canopy\User\lib\site-packages\matplotlib\colorbar.py in <module>()      32 import matplotlib.artist as martist      33 import matplotlib.cbook as cbook ---> 34 import matplotlib.collections as collections      35 import matplotlib.colors as colors      36 import matplotlib.contour as contour  C:\Users\user\AppData\Local\Enthought\Canopy\User\lib\site-packages\matplotlib\collections.py in <module>()      25 import matplotlib.artist as artist      26 from matplotlib.artist import allow_rasterization ---> 27 import matplotlib.backend_bases as backend_bases      28 import matplotlib.path as mpath      29 from matplotlib import _path  C:\Users\user\AppData\Local\Enthought\Canopy\User\lib\site-packages\matplotlib\backend_bases.py in <module>()      54       55 import matplotlib.tight_bbox as tight_bbox ---> 56 import matplotlib.textpath as textpath      57 from matplotlib.path import Path      58 from matplotlib.cbook import mplDeprecation  C:\Users\user\AppData\Local\Enthought\Canopy\User\lib\site-packages\matplotlib\textpath.py in <module>()      17 from matplotlib.path import Path      18 from matplotlib import rcParams ---> 19 import matplotlib.font_manager as font_manager      20 from matplotlib.ft2font import FT2Font, KERNING_DEFAULT, LOAD_NO_HINTING      21 from matplotlib.ft2font import LOAD_TARGET_LIGHT  C:\Users\user\AppData\Local\Enthought\Canopy\User\lib\site-packages\matplotlib\font_manager.py in <module>()    1410                 verbose.report(""Using fontManager instance from %s"" % _fmcache)    1411         except: -> 1412             _rebuild()    1413     else:    1414         _rebuild()  C:\Users\user\AppData\Local\Enthought\Canopy\User\lib\site-packages\matplotlib\font_manager.py in _rebuild()    1395     def _rebuild():    1396         global fontManager -> 1397         fontManager = FontManager()    1398         if _fmcache:    1399             pickle_dump(fontManager, _fmcache)  C:\Users\user\AppData\Local\Enthought\Canopy\User\lib\site-packages\matplotlib\font_manager.py in __init__(self, size, weight)    1050             self.defaultFont['ttf'] = self.ttffiles[0]    1051  -> 1052         self.ttflist = createFontList(self.ttffiles)    1053     1054         self.afmfiles = findSystemFonts(paths, fontext='afm') +  C:\Users\user\AppData\Local\Enthought\Canopy\User\lib\site-packages\matplotlib\font_manager.py in createFontList(fontfiles, fontext)     577         else:     578             try: --> 579                 font = ft2font.FT2Font(fpath)     580             except RuntimeError:     581                 verbose.report(""Could not open font file %s""%fpath)  TypeError: cannot return std::string from Unicode object   I get this error on running the following code:  import matplotlib import math import numpy as np import matplotlib.ticker as mticker import matplotlib.pyplot as plt import matplotlib.dates as mdates  def graphRawFX():     date, bid, ask = np.loadtxt('GBPUSD1d.txt', unpack = True, delimiter = ',', converters = {0:mdates.strpdate2num('%Y%m%d%H%M%S')})     fig = plt.figure(figsize=(10,7))     ax1 = plt.subplot2grid((40,40), (0,0), rowspan = 40, colspan = 40)     ax1.plot(date, bid)     ax1.plot(date, ask)          ax1.xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d %H:%M:%S'))          plt.grid(True)     plt.show()   Please help. I don't understand how to solve this.",True
@mrbighit,2014-11-19T09:29:08Z,0,"Any idea where I'm going wrong? I'm using python 3 and the code is giving error:  Traceback (most recent call last):   File ""/Users/mrbighit/Dropbox/Investment/PythonSentDex/machineLearning/tutorialML.py"", line 25, in <module>     graphFX()   File ""/Users/mrbighit/Dropbox/Investment/PythonSentDex/machineLearning/tutorialML.py"", line 13, in graphFX     converters = {0, mdates.strpdate2num('%Y%m%d%H%M%S')})   File ""/usr/local/lib/python3.4/site-packages/numpy/lib/npyio.py"", line 834, in loadtxt     for i, conv in (user_converters or {}).items(): AttributeError: 'set' object has no attribute 'items'  ________________________________________  import matplotlib import matplotlib.pyplot as plt  import matplotlib.ticker as mticker import matplotlib.dates as mdates import numpy as np  	   def graphFX(): 	date, bid, ask = np.loadtxt('GBPUSD1d.txt', unpack = True, 								delimiter = ',',  								converters = {0, mdates.strpdate2num('%Y%m%d%H%M%S')})  	fig = plt.figure(figsize = (10,7)) 	ax1 = plt.subplot2grid((40,40), (0,0), rowspan=40, colspan=40)  	ax1.plot(date, bid) 	ax1.plot(date, ask) 	ax1.xaxis.set_major_formatter(m.dates.DateFormatter('%Y-%m-%d %H:%M:%S'))  	plt.grid(True) 	plt.show()  graphFX()",True
@luxu633,2014-08-17T04:40:37Z,0,"import matplotlib import matplotlib.pyplot as plt import matplotlib.ticker as mticker import matplotlib.dates as mdates import numpy as np  def graphRawFX():     date,bid,ask= np.loadtxt(""GBPUSD1d.txt"",unpack = True,                              delimiter = "","",                              converters={0:mdates.strpdate2num(""%Y%m%d%H%M%S"")})          fig = plt.figure(figsize=(10,7))          ax1 = plt.subplot2grid((40,40),(0,0),rowspan=40, colspan = 40)          ax1.plot(date,bid)                   ax1.plot(date,ask)      ax1.xaxis.set_major_formatter(mdates.DateFormatter(""%Y-%m-%d %H:%M:%S""))          plt.grid(True)          plt.show      print(1)      when i run this, this comes out   Python 2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)] on win32 Type ""copyright"", ""credits"" or ""license()"" for more information. >>> ================================ RESTART ================================ >>>  >>> graphRawFX() 1 >>>    But not the graph...  Can you help me figure out? please...",True
@oliverinsulander,2014-07-28T10:07:22Z,0,"Hi, i get the following error when running this, I also got the same error when doing another tutorial of yours. Any Ideas.  Python 2.7.6 (default, Nov 10 2013, 19:24:24) [MSC v.1500 64 bit (AMD64)] on win32 Type ""copyright"", ""credits"" or ""license()"" for more information. >>> ================================ RESTART ================================ >>>  Traceback (most recent call last):   File ""C:\Python27\machinLearning\AlgoTrading.py"", line 14, in <module>     ax1.plot(date,bid) NameError: name 'date' is not defined >>>",True
@adviceradvicerov8469,2014-05-26T17:34:47Z,0,"Awesome tutorials. Can you add one about pyqtgraph, pyqwt or integration of matplotlib to qt gui? With realtime graphing? May be, you have such tutorials, I didn't find.",True
@davedavids3407,2014-04-26T20:52:28Z,0,"Hey sentdex amazing tutorials i'm slowly working my way through them all.  I'm getting the error ValueError: invalid literal for float(): 20130501000000,1.55358,1.55371  Cant figure it out.",True
@yashescooll,2014-04-23T20:26:05Z,0,"when i try to do import matplotlib.pylot as plt it tells me that i have no module named pylot. I got scipy numpy and matplotlib in a ""SciPy Superpack"" as i was having difficulty importing each separately.",True
@GBowden00,2014-04-05T07:09:57Z,0,"Hi, I would like to thank you for sharing such great programming tutorials. I'm running puthon 2.7.5 on xubuntu. When i run the code I get the following error: File ""fxpatterns.py"", line 15     fig = plt.figure(figaize=(10,7)       ^ SyntaxError: invalid syntax   Thanks",True
@DellBlackberry22,2014-04-01T03:58:51Z,0,"I'm getting a few import error of:  import matplotlib   File ""C:\Python27\lib\site-packages\matplotlib\__init__.py"", line 111, in <module>     raise ImportError(""matplotlib requires dateutil"") ImportError: matplotlib requires dateutil I resolved that but here is my problem now:     import matplotlib.pyplot as plt   File ""C:\Python27\lib\site-packages\matplotlib\pyplot.py"", line 29, in <module>     from matplotlib.figure import Figure, figaspect   File ""C:\Python27\lib\site-packages\matplotlib\figure.py"", line 36, in <module>     from matplotlib.axes import Axes, SubplotBase, subplot_class_factory   File ""C:\Python27\lib\site-packages\matplotlib\axes.py"", line 20, in <module>     import matplotlib.dates as _  # <-registers a date unit converter   File ""C:\Python27\lib\site-packages\matplotlib\dates.py"", line 119, in <module>     from dateutil.rrule import (rrule, MO, TU, WE, TH, FR, SA, SU, YEARLY,   File ""C:\Python27\lib\site-packages\dateutil\rrule.py"", line 18, in <module>     from six import advance_iterator, integer_types ImportError: No module named six  This is what I have: import matplotlib import matplotlib.pyplot as plt import matplotlib.ticker as mticker import matplotlib.dates as mdates import numpy as np  def graphRawFX():     date,bid,ask = np.loadtxt('GBPUSD1d.txt', unpack=True,                               delimiter=',',                               converters={0:mdates.strpdata2num('%Y%m%d%H%M%S')})     fig = plt.figure(figsize =(10,7))     ax1 = plt.subplot2grid((40,40),(0,0), rowspan=40, colspan=40)      ax1.plot(date,bid)     ax1.plot(date,ask)      ax1.xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d %H: %M: %S'))      plt.grid(True)     plt.show()",True
@henryt9304,2014-03-02T16:20:03Z,0,I am having a hard time of where I should extract the GBPUSD Text files so that Python could run through raw data. Could someone help? Thanks,True
@abhis91,2014-02-15T15:37:33Z,0,Good tutorial series ! cant wait to get to the end,True
@zpydaz90,2013-12-10T06:58:06Z,0,"i placed both text files into the directory, though when I press enter it gives me a syntax error.",True
@zpydaz90,2013-12-10T06:51:27Z,0,I'm having problems pulling up the chart..they say graphrawFX() is not defined. I'm trying to figure out if its where I placed the GBPUSD files. Any help?,True
@4yt158,2013-11-15T08:41:35Z,4,"Hi,  Thanks for the great tutorial.  I'm new to Python and using Python3.3. Looks like 'strpdate2num' in the code in the video gives this error: http://stackoverflow.com/questions/16496017/typeerror-when-using-matplotlibs-strpdate2num-with-python-3-2  After using the help from stackoverflow, was able to get the output graph! :) Here is the code: import matplotlib import matplotlib.pyplot as plt import matplotlib.ticker as mticker import matplotlib.dates as mdates import numpy as np  def bytedate2num(fmt):     def converter(b):         return mdates.strpdate2num(fmt)(b.decode('ascii'))     return converter  def graphRawFx():     date,bid,ask = np.loadtxt('GBPUSD1d.txt', unpack=True,delimiter="","",converters={0:bytedate2num('%Y%m%d%H%M%S')})     fig=plt.figure(figsize=(10,7))     ax1 = plt.subplot2grid((40,40),(0,0), rowspan=40, colspan=40)     ax1.plot(date,bid)     ax1.plot(date,ask)     ax1.xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d %H:%M:%S'))     plt.grid(True)     plt.show()",True
@deanmagee4245,2013-11-07T11:31:58Z,0,These videos are great. Keep them coming.  Much appreciated. ,True
