author,updated_at,like_count,text,public
@muhammadali-jv1kr,2020-12-12T12:39:28Z,0,List INdex out of range errror any guidance plz,True
@jwanamedi2890,2020-11-01T15:08:32Z,1,"The video is very helpful but I got this error  ""VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray   return array(a, dtype, copy=False, order=order, subok=True)   0%|          | 0/25000 [00:00<?, ?it/s] "".  I don't know how to fix it can you please help me to solve this error and thank you in advance",True
@buggyfifa,2020-10-11T23:29:27Z,0,No module named 'tensorflow.contrib' any help,True
@nishantnishu5183,2020-08-12T09:59:57Z,0,"Have been trying this code on python 3.7.7 Tensor flow 1.15 ,later tensor flow 1.14,then 1.13.0  It's doesn't work in them  Constantly been getting the message ""no module named tensor flow""  What do u suggest brother ?  It will be really helpful if you reply to it thank you",True
@marcusbranch2100,2020-07-12T22:18:11Z,1,"testing_data.append([np.array(img), img_num])                ^ SyntaxError: invalid syntax   anyone know how to fix this error???",True
@varshinis6930,2020-07-10T10:43:05Z,0,AttributeError: module 'tensorflow.python.framework.op_def_registry' has no attribute 'register_op_list'  Does anyone get this error ?  I need help thanks in advance,True
@user-rr8ts6uv5u,2020-06-26T12:45:11Z,0,how to get rid of this error ->ModuleNotFoundError: No module named 'tflearn',True
@yummystore30,2019-12-11T14:41:29Z,4,ModuleNotFoundError: No module named 'tensorflow.contrib  (how to fix it ),True
@hopedental8361,2019-06-13T23:16:40Z,0,"Can someone help me solve this error: File ""C:\Users\snehal\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py"", line 3296, in run_code     exec(code_obj, self.user_global_ns, self.user_ns)    File ""<ipython-input-1-a4737a9c82e8>"", line 1, in <module>     runfile('C:/Users/snehal/.spyder-py3/temp.py', wdir='C:/Users/snehal/.spyder-py3')    File ""C:\Users\snehal\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py"", line 786, in runfile     execfile(filename, namespace)    File ""C:\Users\snehal\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py"", line 110, in execfile     exec(compile(f.read(), filename, 'exec'), namespace)    File ""C:/Users/snehal/.spyder-py3/temp.py"", line 8     Train_dir =pd.read_csv'C:\Users\snehal\Desktop\Learninmg CNN Object_Detection\test'                                                                                       ^ SyntaxError: invalid syntax",True
@timejason4616,2019-05-30T19:34:12Z,0,"Great video, great code, great everything.",True
@user-jc4oi1xg1z,2019-04-18T21:23:31Z,2,Sth is wrong here: word_label = img.split('.')[-3],True
@user-jc4oi1xg1z,2019-04-18T21:19:19Z,0,"Please, could anyone explain the error?  Traceback (most recent call last):   File ""C:/Users/Yaroslav Balytskyi/PycharmProjects/Examples/CNN_Dogs_vs_Cats.py"", line 56, in <module>     train_data = create_train_data()   File ""C:/Users/Yaroslav Balytskyi/PycharmProjects/Examples/CNN_Dogs_vs_Cats.py"", line 33, in create_train_data     label = label_img(img)   File ""C:/Users/Yaroslav Balytskyi/PycharmProjects/Examples/CNN_Dogs_vs_Cats.py"", line 21, in label_img     word_label = img.split('.')[-3] IndexError: list index out of range",True
@spbs-wb9wt,2019-03-25T14:59:58Z,1,IndexError: list index out of range??,True
@vatsaldholakiya4991,2019-03-18T07:43:48Z,0,"i keep getting ValueError: Cannot feed value of shape (64, 50, 50, 1) for Tensor 'input/X:0', which has shape '(?, 28, 28, 1)' can anyone explain?",True
@adityaRaj-uh7es,2018-12-18T09:01:35Z,0,"could you please provide me the ""training.npy"" and  ""test.npy"" file  ? It's taking too long on my system.",True
@santoshmore119,2018-12-13T13:07:45Z,0,"I am getting error   TypeError: float() argument must be a string or a number, not 'NoneType'    at model.fit({'input': X}, {'targets': Y}, n_epoch=5, validation_set=({'input': test_x}, {'targets': test_y}),            snapshot_step=500, show_metric=True, run_id=MODEL_NAME)     please help me to resolve the issue",True
@wpontog,2018-12-12T11:16:39Z,0,"Hi Thanks in advance when i run       train_data = create_train_data()   i get this error --------------------------------------------------------------------------- NameError                                 Traceback (most recent call last) <ipython-input-1-40719067ea74> in <module>() ----> 1 train_data = create_train_data()  NameError: name 'create_train_data' is not defined  Can you help me?",True
@rnkuu,2018-12-01T17:18:14Z,0,do we need to resize images if they are all in the same size??,True
@nicksonoinam5953,2018-10-14T13:50:59Z,0,"IndexError                                Traceback (most recent call last) <ipython-input-12-d2caef02e28f> in <module>() ----> 1 train_data = create_train_data()       2 # If you have already created the dataset:       3 #train_data = np.load('train_data.npy')  <ipython-input-9-f710e9090bc4> in create_train_data()       2     training_data = []       3     for img in tqdm(os.listdir(TRAIN_DIR)): ----> 4         label = label_img(img)       5         path = os.path.join(TRAIN_DIR,img)       6         img = cv2.imread(path,cv2.IMREAD_GRAYSCALE)  <ipython-input-8-45190782d93e> in label_img(img)       1 def label_img(img): ----> 2     word_label = img.split('.')[-3]       3     # conversion to one-hot array [cat,dog]       4     #                            [much cat, no dog]       5     if word_label == 'cat': return [1,0]  IndexError: list index out of range  I am facing this problem while training data, can anyone help me",True
@shienaannwico,2018-10-14T07:09:18Z,0,Hello sentdex! what is the name of the cnn architecture that you use in this video? thankssss,True
@souha5188,2018-09-11T08:13:10Z,0,can I do the same process for videos ??? not images ???,True
@shubhampaul6559,2018-08-23T19:59:47Z,0,"While trying out that, tensorboard_dir encountered an error.  I was using Anaconda on windows. I did what you said about running it on windows.   (tensorflow.python.framework.errors_impl.InvalidArgumentError: Failed to create a directory: log/D:; Invalid argument)  Can you give any more suggestions? Thanks.",True
@hamzamahmood5232,2018-07-28T10:40:00Z,0,can i do the same with different types of wood planks.reply plx,True
@kalankasiyambalapitiya7615,2018-07-16T09:00:03Z,0,I got the `no module named _pywrap_tensorflow` error when trying this on python 3.7 version..what may be the issue?,True
@mockingbird3809,2018-07-06T16:05:26Z,2,I am getting this error.....how to slove it?? ValueError: setting an array element with a sequence,True
@manankumawat8364,2018-05-28T04:46:54Z,0,"*I'm getting this error please help me while building cnn layers* OSError                                   Traceback (most recent call last) c:\users\milind\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\platform\self_check.py in preload_check()      61         try: ---> 62           ctypes.WinDLL(build_info.nvcuda_dll_name)      63         except OSError:  c:\users\milind\appdata\local\programs\python\python36\lib\ctypes\__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)     347         if handle is None: --> 348             self._handle = _dlopen(self._name, mode)     349         else:  OSError: [WinError 126] The specified module could not be found  During handling of the above exception, another exception occurred:  ImportError                               Traceback (most recent call last) <ipython-input-1-8507f364adee> in <module>() ----> 1 import tflearn       2 from tflearn.layers.conv import conv_2d, max_pool_2d       3 from tflearn.layers.core import input_data, dropout, fully_connected       4 from tflearn.layers.estimator import regression       5   c:\users\milind\appdata\local\programs\python\python36\lib\site-packages\tflearn\__init__.py in <module>()       2        3 # Config ----> 4 from . import config       5 from .config import is_training, get_training_mode, init_graph       6   c:\users\milind\appdata\local\programs\python\python36\lib\site-packages\tflearn\config.py in <module>()       1 from __future__ import division, print_function, absolute_import       2  ----> 3 import tensorflow as tf       4        5 from .variables import variable  c:\users\milind\appdata\local\programs\python\python36\lib\site-packages\tensorflow\__init__.py in <module>()      22       23 # pylint: disable=g-bad-import-order ---> 24 from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import      25 # pylint: disable=wildcard-import      26 from tensorflow.tools.api.generator.api import *  # pylint: disable=redefined-builtin  c:\users\milind\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\__init__.py in <module>()      47 import numpy as np      48  ---> 49 from tensorflow.python import pywrap_tensorflow      50       51 # Protocol buffers  c:\users\milind\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>()      28 # Perform pre-load sanity checks in order to produce a more actionable error      29 # than we get from an error during SWIG import. ---> 30 self_check.preload_check()      31       32 # pylint: disable=wildcard-import,g-import-not-at-top,unused-import,line-too-long  c:\users\milind\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\platform\self_check.py in preload_check()      68               ""'C:\\Windows\\System32'. If it is not present, ensure that you ""      69               ""have a CUDA-capable GPU with the correct driver installed."" ---> 70               % build_info.nvcuda_dll_name)      71       72       if hasattr(build_info, ""cudart_dll_name"") and hasattr(  ImportError: Could not find 'nvcuda.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Typically it is installed in 'C:\Windows\System32'. If it is not present, ensure that you have a CUDA-capable GPU with the correct driver installed.   ​",True
@koshkaguan6802,2018-05-21T05:44:11Z,0,Really like your videos!!<3,True
@daminisharma4539,2018-03-22T10:51:09Z,1,NameError                                 Traceback (most recent call last) <ipython-input-3-3a46efe24c12> in <module>() ----> 1 train_data = create_train_data()       2 #if you already have train data       3 #train_data = np_load('train_data.py)  NameError: name 'create_train_data' is not defined getting this error,True
@harunurrashidnayem4488,2018-02-26T19:11:43Z,0,"error : curses is not supported on this machine,when import tflearn.how to fix the error.can anyone help me?",True
@ssesefsefa,2018-01-24T12:20:00Z,0,"I am student from Turkey. I have a graduation project in tihs year. And i have a few days to finish that.My project is detecting street animals. So they are : Cats,Dogs and birds. I checked up your tutorial ""Classifying Cats and Dosg"" but i need triple version of this. So classifying multiple(3 enough for me) images. How can i do this using your method? Please help me.  Regards.",True
@jasonchong8330,2018-01-15T12:51:21Z,0,"TypeError                                 Traceback (most recent call last) <ipython-input-5-52a048b75847> in <module>() ----> 1 train_data = create_train_data()       2 #if you already have train data:       3 #train_data = np.load('train_data.npy)  <ipython-input-3-5f75b8d1ea2a> in create_train_data()       2     training_data = []       3     for img in tqdm(os.listdir(TRAIN_DIR)): ----> 4         label = label_img()       5         path = os.path.join(TRAIN_DIR,img)       6         img = cv2.resize(cv2.imread(path, cv2.IMREAD_GRAYSCALE),(IMG_SIZE,IMG_SIZE))  TypeError: label_img() missing 1 required positional argument: 'img'  HI I GET THIS EEROR WHEN I RUN IT..please helppppp",True
@imamdigmi,2017-12-08T12:15:22Z,0,"Thanks for the great video sir! but when i'm trying to run this code : model.fit({'input': X}, {'targets': Y}, n_epoch=5, validation_set=({'input': test_x}, {'targets': test_y}),      snapshot_step=500, show_metric=True, run_id=MODEL_NAME)  I've got some error like this : InvalidArgumentError: You must feed a value for placeholder tensor 'targets_1/Y' with dtype float and shape [?,2]   [[Node: targets_1/Y = Placeholder[dtype=DT_FLOAT, shape=[?,2], _device=""/job:localhost/replica:0/task:0/device:GPU:0""]()]]  what should i do to solve that problem? and why i'm getting the error like that? thanks a lot.",True
@onofrioallegretta9883,2017-12-01T14:01:11Z,1,"hi, I run code but I received this error: ModuleNotFoundError                       Traceback (most recent call last) <ipython-input-7-b83400946d81> in <module>()       2 #pip install tfLearn       3 #pip install tqdm ----> 4 import cv2       5 import numpy as np       6 import os  ModuleNotFoundError: No module named 'cv2'  Which is the problem?",True
@wosleepy,2017-11-26T18:00:06Z,2,"Thanks for the great video!  I got this problem only under Windows(Ubuntu works perfectly). Please some1 could explain how to fix this. Many thanks!  100%|█████████████████████████████████▉| 24950/25001 [00:23<00:00, 1056.40it/s] --------------------------------------------------------------------------- IndexError                                Traceback (most recent call last) <ipython-input-5-d2caef02e28f> in <module>() ----> 1 train_data = create_train_data()       2 # If you have already created the dataset:       3 #train_data = np.load('train_data.npy')  <ipython-input-3-77364ddd2fa9> in create_train_data()       2     training_data = []       3     for img in tqdm(os.listdir(TRAIN_DIR)): ----> 4         label = label_img(img)       5         path = os.path.join(TRAIN_DIR,img)       6         img = cv2.imread(path,cv2.IMREAD_GRAYSCALE)  <ipython-input-2-45190782d93e> in label_img(img)       1 def label_img(img): ----> 2     word_label = img.split('.')[-3]       3     # conversion to one-hot array [cat,dog]       4     #                            [much cat, no dog]       5     if word_label == 'cat': return [1,0]  IndexError: list index out of range",True
@jbroussard761,2017-11-12T02:18:44Z,0,"Something odd is happening with mine, its like it will make the training set fine but slowly get slower and slower as far as rate of it/s until its an absurd speed and I cancel it.  I have a really fast processor, as well as graphics cards, any idea what could be causing this?  I'm also using native python not jupyter.",True
@aarontal809,2017-09-19T18:47:17Z,0,"I have a quick question regarding the pooling you did: The code on your website ( https://pythonprogramming.net/convolutional-neural-network-kats-vs-dogs-machine-learning-tutorial/ )  uses a kernel size of 5 for the max_pool_2d instead of 2 as shown in your video. Comparing both codes I figured that using a kernel size of 5 yields a better result for me, however I do not understand why this throws no errror with an image size of 50x50 px since pooling 5 times with a kernel size of 5 should make the output of the last layers so small (width and height) that they do not have integer values anymore or am I wrong? If so, whats the dimension of the fully connected_layer in the code on your website?   Thank you very much in advance! And keep up your awesome work!",True
@zosamohakaziz8185,2017-09-04T22:43:59Z,0,"i get this error Traceback (most recent call last):   File ""C:\Users\DELL\Desktop\cat ve dog\cat vs dog.py"", line 48, in <module>     train_data = create_train_data()   File ""C:\Users\DELL\Desktop\cat ve dog\cat vs dog.py"", line 23, in create_train_data     for img in tqdm(os.listdir(TRAIN_DIR)): WindowsError: [Error 123] La syntaxe du nom de fichier, de répertoire ou de volume est incorrecte: 'C:\\Users\\DELL\\Desktop\\cat ve dog\test/*.*'",True
@sergetheamazing,2017-08-30T14:50:30Z,1,How can I do this without using Jupyter? I tried running the code but it took far too long :(,True
@pallavbakshi7941,2017-08-20T09:46:36Z,0,awesome,True
@AddyKanhere,2017-07-30T18:33:50Z,0,"Hey loved this tutorial. However when I try to preprocess the data I get this message | 0/25000 [00:00<?, ?it/s] and there seems to be nothing happening. Could you please help me on this.",True
@quocthanhtran4876,2017-07-29T11:26:41Z,0,"Hello,  I can't read the data from my local drive using Kaggle notebook. I'm using windows8 and it can't figure out the path. Can someone help?",True
@ParthVadhadiya,2017-05-19T10:38:20Z,0,"encountered 'list index out of range' error. python error,  when we fire some position on list but there is no value at that position available for use.. but in our case we use properly split funtion. then to this error repeatedly bothering me",True
@muhammadhannan6701,2017-05-17T14:56:21Z,0,"+sendex can you tell me why I'm getting this error100%|███████████████████████████████████████████████████████████████████████████▉| 24992/25001 [05:40<00:00, 73.49it/s] --------------------------------------------------------------------------- error                                     Traceback (most recent call last) <ipython-input-15-bbbaeea53095> in <module>() ----> 1 train_data = create_train_data()  <ipython-input-13-f710e9090bc4> in create_train_data()       5         path = os.path.join(TRAIN_DIR,img)       6         img = cv2.imread(path,cv2.IMREAD_GRAYSCALE) ----> 7         img = cv2.resize(img, (IMG_SIZE,IMG_SIZE))       8         training_data.append([np.array(img),np.array(label)])       9     shuffle(training_data)  error: C:\projects\opencv-python\opencv\modules\imgproc\src\imgwarp.cpp:3492: error: (-215) ssize.width > 0 && ssize.height > 0 in function cv::resize ?",True
@adusalmi4334,2017-05-03T07:37:04Z,0,"Hi Sentdex; something doesn't work for me, is that line : word_label = img.split('.')[-3]  it appears the coming error :  Traceback (most recent call last):   File ""C:\dataset\capsule_classifier.py"", line 41, in <module>     train_data = create_train_data()   File ""C:\dataset\capsule_classifier.py"", line 27, in create_train_data     img = cv2.resize(cv2.imread(path,cv2.IMREAD_GRAYSCALE), (IMG_SIZE,IMG_SIZE)) cv2.error: C:\bld\opencv_1489520410290\work\opencv-3.1.0\modules\imgproc\src\imgwarp.cpp:3229: error : (-215) ssize.area() > 0 in function cv::resize  i need help, i think the -3 is the issue, No ?",True
@nicolaadrianopallottino3708,2017-04-26T14:23:59Z,0,why don't you use 'binary crossentropy'? we have got a binary classification. And my output is 'curses is not supported on this machine (please install/reinstall curses for an optimal experience)'. What should I install? Can you link me? thanks :),True
@ryanshrott9622,2017-04-24T18:03:25Z,0,I like that you link the actual tutorial in your video:),True
@ridarsyed,2017-04-13T14:46:23Z,1,"what if we classify 7 different things we should use  if word_label == 'cat': return [0,0,0,0,0,0,1]",True
@urvishnakum914,2017-03-20T19:32:33Z,0,"Sir ,   One Question in mind  after making the model if i got the more training data then how can i modify the existing model without the old training data ?  Is that possible  ?",True
@alexanderlyabah7229,2017-03-01T16:47:51Z,0,"Cool video, that explains how to use FOR and copy-paste from tutorials.",True
@vsigal,2017-03-01T12:26:53Z,0,"for which version of TF is it. I have 1.0 and could not run tf tflearn  ...  ValueError: Only call `softmax_cross_entropy_with_logits` with named arguments (labels=..., logits=..., ...)",True
@paulinocristovao9856,2017-02-25T04:58:26Z,0,great tutorials. instead of tflearn maybe you could have a look  on pretty tensor .,True
@harutakakawamura9240,2017-02-22T23:08:06Z,0,That progress bar is really cool!,True
@ulm287,2017-02-22T19:33:55Z,0,Great Video series. My go to channel for neuronets,True
@lanvukusic,2017-02-22T16:20:50Z,2,Why did you choose grayscale? im quite new to it. Wuld we benefit with separete r g b channels? Best regards,True
@lanvukusic,2017-02-22T16:17:31Z,22,"That is probably THE best tuttorial for anyone who tries to make a clasifier in tensorflow from groun up, with his own images. really great content.",True
