author,updated_at,like_count,text,public
@nothingDone-ei2fj,2024-01-07T04:44:54Z,0,"def grab_initial_state_data():     states = state_list()      main_df = pd.DataFrame()      for abbv in states:         query = ""FMAC/HPI_""+str(abbv)         df = quandl.get(query, authtoken=api_key)         df.rename(columns={'NSA Value':str(abbv)+'_NSA Value','SA Value':str(abbv)+'_SA Value'}, inplace=True)         print(query)         df[abbv] = (df[abbv]-df[abbv][0]) / df[abbv][0] * 100.0         print(df.head())         if main_df.empty:             main_df = df         else:             main_df = main_df.join(df)                  pickle_out = open('fiddy_states3.pickle','wb')     pickle.dump(main_df, pickle_out)     pickle_out.close() #print(df.head())    grab_initial_state_data()  HPI_data = pd.read_pickle('fiddy_states3.pickle')  HPI_data.plot() plt.legend().remove() plt.show()   I got an error.  FMAC/HPI_AK --------------------------------------------------------------------------- KeyError                                  Traceback (most recent call last) File ~\anaconda3\Lib\site-packages\pandas\core\indexes\base.py:3653, in Index.get_loc(self, key)    3652 try: -> 3653     return self._engine.get_loc(casted_key)    3654 except KeyError as err:  File ~\anaconda3\Lib\site-packages\pandas\_libs\index.pyx:147, in pandas._libs.index.IndexEngine.get_loc()  File ~\anaconda3\Lib\site-packages\pandas\_libs\index.pyx:176, in pandas._libs.index.IndexEngine.get_loc()  File pandas\_libs\hashtable_class_helper.pxi:7080, in pandas._libs.hashtable.PyObjectHashTable.get_item()  File pandas\_libs\hashtable_class_helper.pxi:7088, in pandas._libs.hashtable.PyObjectHashTable.get_item()  KeyError: 'AK'  How can I solve it?",True
@betllatrix534,2020-08-06T05:27:05Z,0,No handles with labels found to put in legend. some one please god dam help,True
@anirbanghosh6328,2020-01-13T14:14:15Z,0,"when i print the list of US abbv it starts from AL, AK..... but when it use them to print the dataset, it starts from AL.... n the last one is without any abbv . Can anyone help me out with it?",True
@daisydiary1895,2019-02-15T00:25:22Z,2,"""All those prices seem to converge perfectly in 2000! Well, this is just when the 100.0% of the index starts. ""  I really can't understand here. Could anybody help? I really appreciate it.",True
@kevinalexanderchicaemeordo3657,2019-02-11T15:52:40Z,0,"I have a proble with df[abrev]=(df[abrev] - df[abrev][0])/df[abrev][0]*100.0 ,    KeyError error is presented: 'AK'",True
@joro8604,2019-02-09T01:59:18Z,2,"To make this work properly, I had to do this.   def grab_initial_state_data():     states = state_list()     main_df = pd.DataFrame()  # creates just an empty dataframe      for abbv in states:         query = ""FMAC/HPI_"" + str(abbv)         df = quandl.get(query, authtoken=api_key)          df.rename(columns={'NSA Value': str(abbv) + ' NSA Value', 'SA Value': str(abbv) + ' SA Value'}, inplace=True)          col_abbv_string = str(str(abbv) + ' NSA Value') #set up string for convenience in formula below          # df = df.pct_change()  #do change to percent change. This works stand alone         # formula version for pct change [0] is the original date value of 1970 or whatever         df[col_abbv_string] = (df[col_abbv_string] - df[col_abbv_string][0]) / df[col_abbv_string][0] * 100.0          if main_df.empty:             main_df = df          else:             main_df = main_df.join(df)             print(main_df.head())",True
@kevinalexanderchicaemeordo3657,2019-02-08T20:32:26Z,0,"I have a problem with the Api_Key (I already register and I have the KEY API of quandl), in the code df = quandl.get (query, authtoken = api_key) the following error appears: raise klass (message, resp.status_code, resp. text, resp.headers, code)  NotFoundError: (Status 404) (Quandl Error QECx02) You have submitted an incorrect Quandl code. Please check your Quandl codes and try again. I'm attentive to any suggestions thanks.",True
@louisscicluna5680,2019-02-01T14:27:38Z,0,"hi, i am mainly starting out and using jupyter from anaconda, will the code still work?",True
@KarthikRampur-ql2td,2018-12-22T01:54:44Z,1,"qunadlÂ now a days return NSA and SA columns i.e 2columns instead of 1 column.if this is the case use below method use can also use for loop if you have many columns.  def get_initial_state_data():     states = get_state_list()                                main_df = pd.DataFrame()     # get All the state Abbrevations     for abbv in states:         query = ""FMAC/HPI_""+str(abbv)         df = quandl.get(query ,authtoken= api_key)         df.rename(columns={'NSA Value':str(abbv) + '_NSA Value' , 'SA Value' : str(abbv) + '_SA Value'},inplace=True)         df[str(abbv) + '_NSA Value'] = (df[str(abbv) + '_NSA Value']-df[str(abbv) + '_NSA Value'][0]) / df[str(abbv) + '_NSA Value'][0] * 100.0         df[str(abbv) + '_SA Value'] = (df[str(abbv) + '_SA Value']-df[str(abbv) + '_SA Value'][0]) / df[str(abbv) + '_SA Value'][0] * 100.0         if main_df.empty:             main_df = df         else:             main_df = main_df.join(df)   def HPI_Benchmark():     df_bmark = quandl.get(""FMAC/HPI_USA"", authtoken=api_key)     df_bmark.rename(columns={'NSA Value':'US' + '_NSA Value' , 'SA Value' : 'US' + '_SA Value'},inplace=True)     df_bmark['US' + '_NSA Value'] = (df_bmark['US' + '_NSA Value']-df_bmark['US' + '_NSA Value'][0]) /                 df_bmark['US' + '_NSA Value'][0] * 100.0     df_bmark['US' + '_SA Value'] = (df_bmark['US' + '_SA Value']-df_bmark['US' + '_SA Value'][0]) / df_bmark['US'+ '_SA Value'][0] * 100.0          return df_bmark  fig = plt.figure() ax1 = plt.subplot2grid((1,1), (0,0)) HPI_data = pd.read_pickle('fiddy_states2.pickle') benchmark = HPI_Benchmark() HPI_data.plot(ax=ax1) benchmark.plot(color='k',ax=ax1, linewidth=4)  plt.legend().remove() plt.show()",True
@juancruzdominguez8880,2018-11-17T00:15:38Z,0,"I 've got a big red flag when i try to calculate the porcentual variation. Return keyError: 'AL'. Try to rename the columns of df, but kept returning error: ""ValueError: Length mismatch: Expected axis has 2 elements, new values have 1 elements"".  The tables now have two columns for each state, maybe i missing something or the code have to change for work correctly. I'ts a shame because can't move forward beyond this point and I like the tutorial.",True
@saikrishna2000,2018-10-14T14:16:14Z,0,Is the 'benchmark' sort of an average of all the data of all the states?,True
@tejasbargal130,2018-09-03T15:41:06Z,0,If anyone gets error at join use  df.columns = [abbv] after quandl.get,True
@volkan540,2018-08-26T11:56:15Z,0,I really wonder what happened in the 1999-2000 so all the prices started to went up.,True
@Dockmark5,2018-07-24T17:52:42Z,0,"When I add df = df.pct_change(), it still prints out the way it did originally, as a normal graph and not percent change. Any ideas on why ?",True
@mozarter86,2018-07-13T20:47:46Z,0,"There is actually a problem when you making percentages data by doing like        ""df[abbv] = (df[abbv]-df[abbv][0]) / df[abbv][0] * 100.0"" it could be minus value, which does not make sense in percentage",True
@andyhutch1152,2018-07-05T18:35:15Z,1,This is so interesting man. Thank you so much.,True
@rashidal-mahmud1917,2018-06-18T13:43:18Z,0,k is the representation of my dick,True
@sagardnyane3813,2018-04-13T10:51:59Z,0,df[abbv] = (df[abbv] - df[abbv][0] / df[abbv] * 100.0) can you explain it  i cant understand,True
@rockymayank12,2018-03-12T20:14:55Z,0,"raise ValueError(""'transform' must be an instance of ""  ValueError: 'transform' must be an instance of 'matplotlib.transform.Transform'  getting this error ?? I'm stuck. help",True
@openflyingleo773,2018-02-07T13:32:52Z,0,"I can't make the chart colorful, they are all blue, so I can't figure out which line belongs to, why?",True
@sanyamgupta5571,2018-01-18T11:31:48Z,0,"Can't really understand why this is happening?? Traceback (most recent call last):   File ""C:\Users\DELL\lib\site-packages\pandas\core\indexes\base.py"", line 2525, in get_loc     return self._engine.get_loc(key)   File ""pandas\_libs\index.pyx"", line 117, in pandas._libs.index.IndexEngine.get_loc   File ""pandas\_libs\index.pyx"", line 139, in pandas._libs.index.IndexEngine.get_loc   File ""pandas\_libs\hashtable_class_helper.pxi"", line 1265, in pandas._libs.hashtable.PyObjectHashTable.get_item   File ""pandas\_libs\hashtable_class_helper.pxi"", line 1273, in pandas._libs.hashtable.PyObjectHashTable.get_item KeyError: 'United States'",True
@aakashuppadhaya4201,2017-11-06T03:48:28Z,0,getting error at legend().remove() that no attribute remove(),True
@BohdanKokovych,2017-10-18T21:23:58Z,0,https://pythonprogramming.net/percent-change-correlation-data-analysis-python-pandas-tutorial/,True
@CH-sj4dr,2017-09-21T03:43:43Z,0,How do you untruncate data frames?,True
@sairam332,2017-08-12T12:29:04Z,0,First of all thank you very much for this tutorial series. May I know the IDE that you are using?,True
@Alexander-ge2zk,2017-08-05T14:21:22Z,0,"You can't really short the housing market. Yeah right, that's what they were saying to Michael Burry in 2008 :D",True
@safaaal-wajidi4606,2017-06-25T17:45:11Z,0,"Perfect, for Time Series data.  Good job!",True
@RokasDesigns,2017-06-18T07:19:09Z,0,can someone help me understand how df[abbv][0] is the 'old' database? what does the [0] refer to?,True
@kmillanr,2017-05-08T16:52:30Z,0,"hi, i'm getting this error: FileNotFoundError: [Errno 2] No such file or directory: 'pickle.pickle'. any clues on how to solve it? I tried pip install pickle but it gives me the same error",True
@MaksimKupfer,2017-04-29T16:59:56Z,0,I find the pd.index to be a useful way to quickly peak at what you are dealing with. Using df.head could get messy if there are to many columns which is usually the case.,True
@OL8able,2017-04-18T02:53:03Z,0,"Hi sentdex, i have doubt here! If i 'add the percent change of all states and divide by 50' from the year '1975-02-28' it should be equal to the percentage change of USA HPI of that same year right?",True
@arturmuellerromanov4438,2017-04-16T09:21:15Z,0,This is not working for me. I am getting a KeyError with 'TX',True
@manofnocountry,2017-03-24T00:59:12Z,0,"Similarly if you are having a problem with df = quandl.get(""FMAC/HPI_USA"", authtoken=api_key) just ensure you enter df.columns = [""United States""] after.",True
@manofnocountry,2017-03-24T00:24:18Z,0,IF you get problems with this code just ensure  df.columns = [str(abbv)]   precedes df[abbv] = (df[abbv]-df[abbv][0]) / df[abbv][0] * 100.0  . There are errors with the code in the video due to the renaming of column names by Quandl.,True
@onirdutta666,2017-02-26T14:28:08Z,1,Is anybody facing a problem after putting the Line: df[abbv] = (df[abbv]-df[abbv][0]) / df[abbv][0] * 100.0  it keeps returning this error: KeyError: 'AL'..Pls Help,True
@juanbarco92,2017-02-24T09:18:23Z,0,"what is the reason of using ptl.show()?. If I run the code without this line, the plot is still showing up. Thanks pythoners",True
@lalu225,2017-02-03T00:06:59Z,0,I am surprised that df[abbv] worked and did not throw an error. I thought that the correct syntax is either df['abbv'] or df.abbv.  I also have a data frame with 1 column and it does not allow me to reference it like Harrison did. Any thoughts?,True
@rodrigosilvanader,2017-01-17T20:18:36Z,0,What are these calculations youÂ´re talking about that start at 100? I dindÂ´t quite get this part and why the values converge at 100...,True
@charliechi762,2016-12-23T06:57:19Z,0,"what is the meaning of this line ""fig = plt.figure()"" ,  I dont get it",True
@SkyRunner18,2016-12-05T20:48:27Z,0,"can someone explain to me how this line of code works, I cant wrap my mind around it  df[abbv] = (df[abbv] - df[abbv][0]) / df[abbv][0] * 100.0",True
@m7807031,2016-10-19T14:28:15Z,1,"I got some problem about join data, and after million times tests I found if you have rename df by df.columns = [str(abbv)], and you could merge dataframe by :           if main_df.empty:             main_df = df         else:             main_df = pd.concat([main_df, df], axis=1)  it works for me and wish it could help others",True
@masterofpuppahs,2016-09-09T15:54:01Z,0,"Hi, starting from Tutorial p7 I am getting an error ValueError: columns overlap but no suffix specified: Index(['Value'], dtype='object'). I copied the code exactly with my own API_key, what is the problem?",True
@kuatroka,2016-08-20T05:54:57Z,2,"Can someone explain me te logic of the this statement please? df[abbv] = (df[abbv] - df[abbv][0] / df[abbv] * 100.0) My understanding was that df[abbv] is the current DataFrame, for example, en entire DataFrame for 'AL' for all the years, meaning it's 498 values. df[sbbv][0] is just the first year's value in the current DataFrame. So how does it work conceptually here that we do mathematics between 498 values and only one value? What does is actually do? it takes percentage change of all the 498 values as reference of the first value? Thanks",True
@alsherbin4420,2016-08-06T14:42:11Z,1,"When I run the same code you have, I get ""FileNotFoundError: [Errno 2] No such file or directory: 'fiddy_states3.pickle'""  Did I miss soemthing or doesn't pickle create the file on the fly?",True
@corey-thompson,2016-07-13T01:17:42Z,12,"FYI the the fact that ""k"" represents black comes from the fact that black is the ""key"" value not because the ""b"" was taken by blue. It comes from the CMYK color model standing for cyan, yellow, magenta, and key. They could have just as easily named the model CMYB. Now you know. =)",True
@gemartintw,2016-06-15T04:29:27Z,11,It seems that quandl changed all columns names to 'Value' I had a problem with that line: df[abbv] = (df[abbv]-df[abbv][0]) / df[abbv][0] * 100.0  it kept returning this error: KeyError: 'AL'  I had to rename the columns in df like this: df = df.rename(columns={'Value': abbv})  Also had to do it for 'United States',True
@Achooification,2016-06-10T22:51:43Z,0,Any plan to allow +=1 via Bitcoin?,True
@suhardisjahrial3318,2016-05-28T18:13:36Z,0,"Hi, when running the program in Video 8, it has this error: ""ImportError: html5lib not found, please install it"". I am using Anaconda 3.4 (64 bit). Thanks Juergen",True
@RealMcDudu,2016-05-10T21:00:16Z,0,"Dude, why did you put the pct_change in the actual query? That's a waste of resources.   You can just run it on the entire data (after it's pickled, and de-pickled).  In the 1st pct_change() it's copy paste to just before the plot. In the 2nd one - you could write this code before the plotting:  for i in range(len(HPI_data.columns)):     HPI_data.iloc[:,i] = 100.0 * (HPI_data.iloc[:,i] - HPI_data.iloc[0,i])/HPI_data.iloc[0,i]",True
@Akashyadav-ue6yc,2016-05-02T06:53:34Z,0,"Hey, I have copy pasted the same code still I'm getting some ""KeyError : 'TX' """,True
@knotriders2882,2016-04-04T04:37:08Z,10,"I put  ""Value"" instead ""United States. It's now work. python 3.5.1. You should check column. df = Quandl.get(""FMAC/HPI_USA"", authtoken=api_key) print(df)",True
@thomasibbotson6499,2015-11-08T22:52:55Z,8,"FYI they changed the column name of ""United States"" to: ""United States                  not seasonally adjusted"" on Quandl... I don't know why.",True
@preferential94,2015-10-07T13:20:17Z,3,"Hey sentdex, I just kept getting this error despite having the exact same code (I even tried copy-pasting the code from your site): Traceback (most recent call last):   File ""D:/My Stuff/Dropbox/Python/Python projects/Learning Pandas/testing 8.py"", line 19, in <module>     benchmark = HPI_Benchmark()   File ""D:/My Stuff/Dropbox/Python/Python projects/Learning Pandas/testing 8.py"", line 12, in HPI_Benchmark     df[""United States""] = (df[""United States""]-df[""United States""][0]) / df[""United States""][0] * 100.0   File ""D:\Programs\Installed\Python34\lib\site-packages\pandas\core\frame.py"", line 1797, in __getitem__     return self._getitem_column(key)   File ""D:\Programs\Installed\Python34\lib\site-packages\pandas\core\frame.py"", line 1804, in _getitem_column     return self._get_item_cache(key)   File ""D:\Programs\Installed\Python34\lib\site-packages\pandas\core\generic.py"", line 1084, in _get_item_cache     values = self._data.get(item)   File ""D:\Programs\Installed\Python34\lib\site-packages\pandas\core\internals.py"", line 2851, in get     loc = self.items.get_loc(item)   File ""D:\Programs\Installed\Python34\lib\site-packages\pandas\core\index.py"", line 1572, in get_loc     return self._engine.get_loc(_values_from_object(key))   File ""pandas\index.pyx"", line 134, in pandas.index.IndexEngine.get_loc (pandas\index.c:3838)   File ""pandas\index.pyx"", line 154, in pandas.index.IndexEngine.get_loc (pandas\index.c:3718)   File ""pandas\hashtable.pyx"", line 686, in pandas.hashtable.PyObjectHashTable.get_item (pandas\hashtable.c:12294)   File ""pandas\hashtable.pyx"", line 694, in pandas.hashtable.PyObjectHashTable.get_item (pandas\hashtable.c:12245) KeyError: 'United States'",True
